### ISSUE TITLE
Representing a complex relationship between exclusive/depedent @Options.

### ISSUE THREAD

**Issue by masupilami** [remkop/picocli#1012]
I'm trying to represent the following relationship between three options `-a`, `-b` and `-c`:

- `-a` and `-b` are mutually exclusive
- `-a` depends on `-c`
- `-b` does not depend on `-c`

So that these combinations are valid:

- `-a -c` 
- `-b -c`
- `-b`
- `-c`
- ` `

And these are invalid:

- `-a -b -c` 
- `-a -b`
- `-a`

This setup works correctly, except for `-b -c`, which is rejected:

```java
@ArgGroup
Exclusive exclusive;

static class Exclusive {
  @ArgGroup(exclusive = false)
  Dependent dependent;
  @Option(names = "-b")
  boolean b;
}

static class Dependent {
  @Option(names = "-a")
  boolean a;
  @Option(names = "-c", required = true)
  boolean c;
}
```
Am I missing something obvious, or is it impossible to enforce this relationship?
thanks

**Comment by remkop** [comment]
Picocli argument groups can express any relationship for which you can write a command line synopsis with every option occurring only once. For example:

```
<cmd> [-c [-a | -b]]
```
or 
```
<cmd> ([-c] -a) | -b
```

But I don’t think that your requirements can be expressed this way. Perhaps the best approach is to make `-a` and `-b` mutually exclusive, and validate in the application that `-c` is present when `-a` was specified. 

A clean way to do this is for the application to throw a `picocli.CommandLine.ParameterException` when this validation fails.

**Comment by masupilami** [comment]
Thanks for the quick reply. This solution works well enough.

**Comment by patric-r** [comment]
Hello everyone,
I'd like to add my 2 cents regarding this issue which we hit as well:

We're currently investigating replacing args4j with picocli.
While picocli seems to be superior in most areas, this issue describes a lack of a feature in picocli which prevents us for doing a 1:1 conversion of the "argument beans" from args4j.

I agree that this kind of argument conventions are rare. 
However, there are legitimate use cases for them and having a support for them would be really nice.

Any chances to see that feature in future picocli releases - or is it unlikely, as its fundamental architectural does not allow this?

Thanks!

**Comment by remkop** [comment]
Hi @patric-r, thanks for considering picocli!

Args4j, with its ability to specify `depends` and `forbids` options on any option, took a different approach to this problem than picocli. Each approach has different trade-offs and applications need to decide which trade-off makes the most sense for them. 

Personally I like that picocli’s approach means that it can automatically generate a synopsis that expresses the relationships between options. I’m not sure if args4j can do this (I haven’t tried).

To answer your question, I won’t rule out the possibility that picocli will support more complex relationships in the future, but it’s currently not on the roadmap. If someone submits a PR for this I will certainly consider it but otherwise it’s not something I see myself working on in the near future.
