### ISSUE TITLE
Main file is too large.

### ISSUE THREAD

**Issue by Linyer-qwq** [remkop/picocli#1025]
Hi! Recent days, I am trying to fix issues of picocli. I think this project is awesome and deserved to learn from. But i find that, the main file is too large. It may be not good for developers to locate issues and debug them. Could you make it more modular?

**Comment by remkop** [comment]
Hi!
I’ve tried to answer that in the FAQ: https://github.com/remkop/picocli/wiki/FAQ

**Comment by Wycers** [comment]
Oh..But it costs so much resources to do tokenization..

**Comment by remkop** [comment]
Having the main functionality (except auto-completion) in a single source files is one of picocli's features. It is advertised in the user manual as one of picocli's benefits, because it **allows applications to use picocli by including the source and not having an external dependency**.

Also, all public nested classes are part of the published API, and cannot be moved without breaking binary compatibility. I **do not want to break binary compatibility**.
Only private and package-protected classes could potentially be moved without breaking binary compatibility, so the benefit of breaking up the source into multiple files is likely limited.

I will consider breaking up the file if we can find solutions to the above two concerns...

**Comment by Linyer-qwq** [comment]
Oh！Thanks for your explanation! That's really an awesome feature. I think I need to get a more powerful computer..... XD
