### ISSUE TITLE
Writer is not flushed after printSuggestions in CommandLine

### ISSUE THREAD

**Issue by darkmoonka** [remkop/picocli#1034]
### Description

The method `printSuggestions` in `picocli.CommandLine` does not `flush` the `writer` at the end of `printSuggestions` method.

### Actual result
The suggestions are not printed automatically, I have to call the `flush` manually on the `PrintWriter` after execution.

### Expected result
The suggestions are printed automatically, so no manual `flush` call is needed.

**Comment by remkop** [comment]
@darkmoonka Thank you for raising this!

I will add a call to `writer.flush()` in the `printSuggestions` implementation.

Can I ask: what writer are you passing in? Could that be a custom writer?
I thought that all `PrintWriters` created by picocli were constructed so that auto-flush is `true`.

But good point that the `printSuggestions` implementation should not rely on that.

**Comment by darkmoonka** [comment]
> @darkmoonka Thank you for raising this!
> 
> I will add a call to `writer.flush()` in the `printSuggestions` implementation.
> 
> Can I ask: what writer are you passing in? Could that be a custom writer?
> I thought that all `PrintWriters` created by picocli were constructed so that auto-flush is `true`.

I just pass `new PrintWriter(err)` to the `setErr` method where `err` is a `PrintStream`.

> 
> But good point that the `printSuggestions` implementation should not rely on that.

@remkop Thanks for the quick feedback!

**Comment by remkop** [comment]
Ok, I was able to reproduce the issue with a BufferedWriter.

Fixed in master now. The fix will be in the next release (picocli 4.3).

Thanks again for raising this!

**Comment by remkop** [comment]
PS.
If you like picocli please star ⭐ the project on GitHub and tell your friends! 😉
