### ISSUE TITLE
Multiple repeatable ArgGroups with positional parameters

### ISSUE THREAD

**Issue by NewbieOrange** [remkop/picocli#1038]
Hi, I was wondering what is expected behaviour for the following code

```java
class Issue1027 {
    @ArgGroup(exclusive = false, multiplicity = "1..4")
    List<StudentGrade> gradeList;

    @ArgGroup(exclusive = false, multiplicity = "1")
    List<StudentGrade> anotherList;
}

Issue1027 bean = new Issue1027();
new CommandLine(bean).parseArgs("Abby 4.0 Billy 3.5 Caily 3.5 Danny 4.0 Frank 3.5".split(" "));
```

The current master branch will throw a `MaxValuesExceededException`, and if I modify the condition to skip fully matched `GroupMatchContainer`, it will throw a `UnmatchedArgumentException`: 

> Unmatched arguments from index 8: 'Frank', '3.5'

It turns out `anotherList[0]` is filled with `{Abby, 4.0}`, and the last `StudentGrade` is unmatched.

If the multiplicity of `anotherList` is set to `*`, then `gradeList.size() == 4` and `anotherList.size() == 5` with no exception thrown.

**Comment by remkop** [comment]
Since there’s no group configured to capture the 5th occurrence, a `MaxValuesExceededException` sounds about right. 

That said, I am looking at some other additional edge cases for #1027. 

ArgCount also includes options, so the current solution doesn’t always work. I’m thinking to enhance GroupMatch and GroupMatchContainer to make them do fine grained position tracking...

**Comment by NewbieOrange** [comment]
Agreed, `GroupMatch` and `GroupMatchContainer` indeed need some enhancement to completely fix the issue.

On a side note, I am running SpotBugs on picocli and found some minor issues (possible NPE, inefficient calls), would you love to have a PR to address these? No behaviour will be changed. (except possibly less `NullPointerException`)

**Comment by remkop** [comment]
Yes please!
