### ISSUE TITLE
Generation of man page via subcommand

### ISSUE THREAD

**Issue by deining** [remkop/picocli#1066]
Feature request, extracted from #1058:

Picocli based application should be giben the ability to generate its own man page on demand (via subcommand). Something like:

```
@Command(name = "mycommand", subcommands = GenerateManPage.class)
public class MyApp implements Runnable {
...
}
```

**Notes from @remkop:**

Currently the logic lives in a private static inner class: `picocli.codegen.docgen.manpage.ManPageGenerator.App`.
One idea is to rename `App` to `Command` and make it public.
Another idea is to remove the innner `App` class altogether and move the annotations and annotated fields to the `ManPageGenerator` class itself.

**Comment by remkop** [comment]
I've started to look at this.
We probably don't want to use the inner `App` command as is, because it has some options that are not really applicable when using the `ManPageGenerator` as a subcommand. Specifically, we probably don't want to give these options:

```
      <classes>...        One or more command classes to generate man pages for.
  -c, --factory=<factoryClass>
                          Optionally specify the fully qualified class name of the custom factory
                            to use to instantiate the command class. If omitted, the default
                            picocli factory is used.
      --[no-]exit         Specify `--exit` if you want the application to call `System.exit` when
                            finished. By default, `System.exit` is not called.
```

When used as a subcommand, users should not need to specify `classes`: instead, we can just use the full hierarchy that the `gen-manpage` subcommand is part of. I added `Util::flattenHierarchy` to get a list of all `CommandSpec` objects in the hierarchy. Our subcommand can then have a `@Spec`-annotated field and pass `spec.root()` to that utility method to get all commands to generate man pages for.

The usage help message for our subcommand may also need to be slightly different from that of the stand-alone `gen-manpage` command.

**Comment by remkop** [comment]
I believe the implementation is complete (docs still todo...)

Could you do me a favour and try this out and let me know what you think?

To use this, let any command (or subcommand) in the application specify `gen-manpage` as a subcommand with the usual  `@Command(subcommands = picocli.codegen.docgen.manpage.ManPageGenerator.class)` syntax.

Users can then specify `<mycommand> gen-manpage --outdir=DIR` to have man pages generated into the specified directory. Omitting the `--outdir` options means man pages are generated in the current directory. (This works the same as if the command was used as a stand-alone command.)

**Comment by deining** [comment]
> Could you do me a favour and try this out and let me know what you think?

I'm glad to assist here.

MWE:

```
1  @Command(subcommands = { ManPageGenerator.class})
2  class CheckSum implements Callable<Integer> {
3
4     // @Parameters(index = "0")
5     // private File file;
6
7     public static void main(String... args) throws Exception {
8         CommandLine cmd = new CommandLine(new CheckSum());
9          System.exit(cmd.execute(args));
10     }
11
12      @Override
13     public Integer call() throws Exception {
14         return 0;
15     }
16 }
```

There are two issues with this code:

1. Once I run the example above, I'm getting
`java.io.FileNotFoundException: .\<main_class>.adoc `
This is most likely because characters `<` and `>` are not allowed in file names.

2. Once I remove the comments in lines 4+5 and run the example again, I'm getting:
```
Missing required parameter: '<file>'
Usage: mycommand <file> [COMMAND]
      <file>
Commands:
  gen-manpage  Generates man pages for all commands in the specified directory.
```

Did you forget to add `helpCommand = true` in the `@Command` annotation of the `ManPageGenerator` command?

**Comment by remkop** [comment]
Fantastic feedback, as usual. Many thanks!

> Did you forget to add `helpCommand = true` in the `@Command` annotation of the `ManPageGenerator` command?

Oops! Yes I forgot to do that. Good catch!  I pushed a fix to master just now.

> Once I run the example above, I'm getting
>`java.io.FileNotFoundException: .\<main_class>.adoc`
> This is most likely because characters `<` and `>` are not allowed in file names.

Another nice catch! Unnamed commands should not cause errors. Fixed now.

**Comment by deining** [comment]
> Unnamed commands should not cause errors. Fixed now.

I can confirm that the fix cures the problem addressed by me.

However, there are other, related scenarios that lead to the same error:

```
@Command(name="star*", subcommands = { ManPageGenerator.class})
class CheckSum implements Callable<Integer> {
```

This results in `java.io.FileNotFoundException: .\star*.adoc`, which is unfortunate IMHO.

I see two remedies:
- an additional replace/substitution operation
- disallow certain characters in the `name` attribute

I would prefer the second option. Maybe there is another, even better approach?

**Comment by remkop** [comment]
Interesting point. I am still thinking this through, but my first thoughts are:

* `<main_class>` is a picocli-generated string; that should not cause problems (and we fixed that now)
* user-specified names are different, they are the responsibility of the developer. Especially the top-level command should contain only characters that can be used in a file name, because it should be possible to store this command in an executable or shell script, like `COMMANDNAME.exe`, `COMMANDNAME.sh`, `COMMANDNAME.bat`, or just `COMMANDNAME`.

Then I realized that subcommands may also have names containing characters that cannot be used in file names, and this is valid (except for our man page problem), since the subcommand is not saved as a separate file.

One idea is that developers can work around this by choosing a "regular" name and use the special characters in aliases, like `@Command(name = "star-star", aliases = "star*")`.

I don't like disallowing certain characters in the `name` attribute just because it may cause problems for generating man pages. If the workaround (to use special characters in aliases only) is not acceptable, then perhaps we will need to do additional character substitutions.

**Comment by deining** [comment]
Your idea with name aliases is great, this is better than disallowing characters.

Is there a way to localize the usage description of the `gen-manpage` command?
I played around with this a bit:
**MWE:**

```
public class ManpageGen {

    @Command(mixinStandardHelpOptions = true,
             resourceBundle = "pkg.Msg", subcommands = ManPageGenerator.class
             )
    static class MainClass implements Runnable {

        public void run() {
        }
    }

    public static void main(String[] args) {
        new CommandLine(new MainClass()).execute("-h");
    }
}
```

**pkg.Msg.properties:**

```
# Header
usage.headerHeading = First header line%n
usage.header   = Second header line
```

This results in somehow weird usage description output for the `gen-manpage` command:

```
First header line
Second header line
Usage: <main class> [-hV] [COMMAND]
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
Commands:
  gen-manpage  Second header line
```

Any recommendations here?

**Comment by remkop** [comment]
The description of each subcommand in the command list is taken from the subcommand’s first `header` line, or the first `description` line if it does not have a header defined. ([doc](https://picocli.info/#_usage_help_for_subcommands))

The section [headings](https://picocli.info/#_section_headings) can be used to give each section a title and potentially space between sections. Since the header section is the first section, the `headerHeading` may not be that useful, but I added it for consistency.
