### ISSUE TITLE
Make it possible to let custom converters extend built-in converters

### ISSUE THREAD

**Issue by robert-de-vries** [remkop/picocli#1132]
In case you write a custom converter you can't reuse logic that is already available in a built-in converter.

For example to check if input is an integer that is positive, you now have to check two things:
1) input is an integer
2) input is bigger than 0

Part 1 is already done in the built-in IntegerConverter. Could it be possible to make the built-in converters public and extend from them, so in this case only part 2 has to be checked?

This would reduce code to be written and conforms to the DRY principle.

**Comment by remkop** [comment]
This won't be easy. Some converters use reflection to support APIs that were introduced after Java 5 (notably the java.time classes, and java.nio.file.Path). Picocli can be used with Java 5 and higher, so all public classes can only use Java 5 APIs.

For some other converters, they would introduce a dependency on the [java.sql](https://docs.oracle.com/javase/9/docs/api/java.sql-summary.html) module. Picocli uses reflection, so that it only requires the [java.base](https://docs.oracle.com/javase/9/docs/api/java.base-summary.html) module.

On the other hand, the implementation of the built-in converters is fairly straightforward, so is there really much to be gained in application code by inheriting from or composing the built-in converters?

**Comment by robert-de-vries** [comment]
Thanks for the fast reply.

Seems like your article on https://github.com/remkop/picocli/wiki/JSR-380-BeanValidation pointed me in the right direction.
I now added the @Position annotation instead of using a specific type converter.

Great article anyway!

**Comment by remkop** [comment]
Cool. I did not realize that you were looking to do validation. Glad you found that article.

Thanks for the positive words on picocli! Please star the library on GitHub if you like it. 😉
