### ISSUE TITLE
Is there a way to ignore duplicate @Option annotations with the same name?

### ISSUE THREAD

**Issue by ChrisTrenkamp** [remkop/picocli#1143]
I'm using PicoCLI in combination with a code generator, `Immutables`.  I'm having a problem where `Immutables` is generating duplicate `@Option` methods with the same name:

```java
public final class SomeImmutableBuilder {
    @CommandLine.Option(name="mapfield")
    public final SomeImmutableBuilder mapField(Map<String, ? extends String> mapField) { ... }

    // This causes PicoCLI to crash due to the duplicate entry
    @CommandLine.Option(name="mapfield")
    public final SomeImmutableBuilder putAllMapField(Map<String, ? extends String> mapField) { ... }
}
```

```java
var mixin = new SomeImmutableBuilder(...);
var command = new CommandLine(...);
command.addMixin("mixin", mixin); // <- PicoCLI crashes here due to the duplicate @Option
```

Right now, I don't have a way to configure the code generator to deduplicate the `@Option` fields.  Currently, I'm working around this problem with reflection.

Is there a way to configure PicoCLI to ignore or recover from `@Option`s with the same name?

**Comment by remkop** [comment]
Hi @ChrisTrenkamp, sorry, no, option names must be unique in a picocli command by design. 
I can look at changing this but this is such a fundamental assumption in picocli that it will not be easy...

In a hand-coded application, I would recommend having an `@Option`-annotated method and populate multiple fields from that method, if that is what is needed.

In your use case I am not sure what to recommend. 
Do you know why `Immutables` generates options with the same name? I noticed that the option name is identical to the method parameter name: `mapfield` in both the `mapField` and the `putAllMapField` methods. Can you control the method parameter name? If so, giving them different names may solve the issue. (Sorry, I am unfamiliar with the `Immutables` library, would need to dive in deeper if that does not work...)

**Comment by ChrisTrenkamp** [comment]
I know why Immutables is generating an option with the same name, but haven't found a good way to fix it.

I'll continue using reflection to change the duplicate annotation values at runtime to work around this issue.

Thanks.
