### ISSUE TITLE
Generate @-file for the current arguments with a built-in option

### ISSUE THREAD

**Issue by paul-bjorkstrand** [remkop/picocli#1163]
It would be useful if there was an option to generate and output an @-file with the current command line (excluding this new option). The option would require a value, which would be the path to a target file to generate. If the target file exists, it would need to ask the user (interactively) if they want to overwrite the file.

Ideally, this would be available similar to `mixinStandardHelpOptions`, maybe as `mixinAtFileGenerationOptions`

For example, given the option name `--generate-at-file`, and the cli command + arguments `cli --opt1=opt1value --opt2 param1 param2 'param 3'`:

If you were to execute the following: `cli --generate-at-file=./cli-args --opt1=opt1value --opt2 param1 param2 'param 3'`, by default, a file would be created with the following contents:

```
--opt1=opt1value --opt2 param1 param2 'param 3'
```

If the cli or the user had opted into [the simplified format][1], then it would create the file with the following contents:

```
--opt1=opt1value
--opt2
param1
param2
param 3
```

[1]: https://picocli.info/#_simplified_format

**Comment by remkop** [comment]
I can see how this could be useful.

Do you think you will be able to provide a pull request for this?

We can do this in phases: first provide a public static `CommandLine.GenerateAtFileMixin` nested class that has the `--generate-at-file` and a method that performs the logic. We can add the annotation attribute `@Command(mixinAtFileGenerationOptions)` later.

I am not sure about the interactive confirmation to overwrite an existing file, at least not as the only way. There may be scenarios where users want to overwrite an existing file unconditionally, like when the command is run from a script. One way to deal with that is to have the `GenerateAtFileMixin` method that performs the logic accept a parameter that indicates whether confirmation is required or not. That would mean that applications would use `@Mixin GenerateAtFileMixin myMixin;` rather than `@Command(mixinAtFileGenerationOptions)`, so they can call `myMixin.generateAtFileWithoutConfirmation()` or  `myMixin.generateAtFileWithConfirmation()`, depending on their needs.

Finally, perhaps applications want to pass that responsibility to the end users, so have a `--generate-at-file` option that generates with confirmation, and a `--generate-at-file-force` option that silently overwrites if the file exists.

Thoughts?

**Comment by remkop** [comment]
@paul-bjorkstrand I added [this implementation](https://github.com/remkop/picocli/blob/master/picocli-examples/src/main/java/picocli/examples/atfile/AtFileGenerator.java) to the examples. Still not sure if this should be a built-in feature. Meanwhile the example should be useful for reference. 😄

**Comment by remkop** [comment]
I am thinking more and more that it makes sense for applications to implement this feature.

The example can be a good base and starting point.
I added a link to this example in the [user manual](https://picocli.info/#AtFiles).
What do you think?

**Comment by paul-bjorkstrand** [comment]
I like it. Thanks for digging in further, I didn't have a chance to yet (I am using picocli for a little side project, not my day-job 😀)

**Comment by remkop** [comment]
Thanks for the positive feedback!

It is not always easy to walk the line on what to include in the library and what is best handled by the application.
I am still not 100% sure, but for now I believe this is best handled by the applications themselves.
Hopefully the example code will be a good starting point. 
So, for now, I will close this ticket.
Feel free to add comments or open another one if anything comes up.

Don't forget to star ⭐ picocli on GitHub if you like the project! 😉
