### ISSUE TITLE
I have a question about help option

### ISSUE THREAD

**Issue by JavaDev99** [remkop/picocli#1174]
Hi all
I found in picocli library that I need to define help option in command class.
like this
```
@Option(names = {"-h", "--help"}, usageHelp = true, description = "display this help message")
boolean usageHelpRequested;
```
But I want to check help option without defining help option in command class.
Isn't anyway to check it by command class without defining help option?
like this
```
@CommandLine.Command(name = "help")
public class HelpCommand {}
```

**Comment by remkop** [comment]
Hi @JavaDev99,

you could use [`mixinStandardHelpOptions`](https://picocli.info/#_mixin_standard_help_options) instead of defining a `--help` option, that is what I would recommend:

```java
@Command(name = "myapp", version = "myapp 1.0", mixinStandardHelpOptions = true)
class MyApp implements Runnable {
    @Option(names = "--option", description = "Some option.")
    String option;

    @Override public void run() { // business logic here...
    }

    public static void main(String... args) {
        int exitCode = new CommandLine(new MyApp()).execute(args);
        System.exit(exitCode);
    }
}
```

The `mixinStandardHelpOptions` attribute adds `--help` and `--version` options to the command. You don't need to define these options or check them in your application. The `execute` method will take care of checking for `--help` and `--version` and printing this information when requested; and run the business logic otherwise.

Alternatively, you could add the [built-in `help` subcommand](https://picocli.info/#_built_in_help_subcommand) to your command, like this:

```java
@Command(name = "myapp", subcommands = {picocli.CommandLine.HelpCommand.class})
class MyApp implements Runnable {
    @Option(names = "--option", description = "Some option.")
    String option;

    @Override public void run() { // business logic here...
    }

    public static void main(String... args) {
        int exitCode = new CommandLine(new MyApp()).execute(args);
        System.exit(exitCode);
    }
}
```

Here, the `execute` method will check whether the user specified the `help` subcommand.

Does that answer your question?

**Comment by JavaDev99** [comment]
Thank you for answer
yes it works but there is such kind of problem now
How can I ignore these default options from help usage?
```
-h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
```
They are shown automatically by library
I need to ignore them.

**Comment by remkop** [comment]
When you say "I need to ignore them", do you mean you want to hide them (not display them) in the usage help message?

**Comment by JavaDev99** [comment]
yes I mean that

**Comment by remkop** [comment]
The built-in options added via `mixinStandardHelpOptions = true` are always shown and cannot be hidden.

If you really need to do this, then you cannot use the built-in `mixinStandardHelpOptions` options.
Instead, add `--help` and `--version` [help options](https://picocli.info/#_help_options) to your command class. For example:

```java
@Option(names = {"-V", "--version"}, versionHelp = true, hidden = true, description = "Print version information and exit.")
boolean versionInfoRequested;

@Option(names = {"-h", "--help"}, usageHelp = true, hidden = true, description = "Show this help message and exit.")
boolean usageHelpRequested;
```

As before, if your application uses `CommandLine::execute` in its `main` method your application does not need to check whether the user specified `--help` or `--version`. Picocli will check this automatically and will print this information when requested; and run the business logic otherwise. 

Be aware that this is an unusual thing to do. I would think that most users would expect to see the `--help` and `--version` options in the usage help message. Interesting, why do you want to hide them?

**Comment by JavaDev99** [comment]
thank you very much
I will see what version to use

**Comment by remkop** [comment]
No worries! 👍 

Don't hesitate to star ⭐  picocli on GitHub if you like the project! 😉

**Comment by sysmat** [comment]
When using **picocli.CommandLine.HelpCommand** output of help not user friendly:

```
Usage:

<main class> get [-u=<username>]

Description:

retrive user data

Options:

  -u, --username=<username>
         Specify username
         For example, `-u test`
```

* **main class**    This should not be in terminal

**Comment by remkop** [comment]
@sysmat can you provide steps to reproduce this?

**Comment by remkop** [comment]
@sysmat Would you mind raising a separate ticket? Your question seems related to combining picocli with JLine, rather than about providing a custom -h help option. It may be good to discuss in more depth on a separate ticket.
