### ISSUE TITLE
Update to JLine3 3.16.0

### ISSUE THREAD

**Issue by rnc** [remkop/picocli#1175]
I was having problems configuring a widget in my App which I had configured according to the picocli example. After some discussions on https://github.com/jline/jline3/issues/571 it would seem that if picocli updated to 3.16.0 then this would resolve it.
Thanks!

**Comment by remkop** [comment]
I started to migrate to JLine 3.16, but it must have some backwards-incompatible changes, because the Example in  [picocli-shell-jline3/src/test](https://github.com/remkop/picocli/blob/master/picocli-shell-jline3/src/test/java/picocli/shell/jline3/example/Example.java) no longer compiles... 
This example is also shown in the [README](https://github.com/remkop/picocli/blob/master/picocli-shell-jline3/README.md) so we should update it to the new JLine 3.16 API.

I went ahead added a section to the [README](https://github.com/remkop/picocli/blob/master/picocli-shell-jline3/README.md) on compatible versions; I think it is important to start tracking this.

@mattirn, could I ask you to help migrating the Example to the new JLine 3.16 API?

**Comment by rnc** [comment]
@remkop I've got it compiling and working - although I haven't updated the docs - I'll send a PR for what I have.

**Comment by remkop** [comment]
Great, thank you! I will update the docs in a bit.
Many thanks for the PR!
