### ISSUE TITLE
AnnotationProcessor setup with java maven modules and IntelliJ

### ISSUE THREAD

**Issue by hegerdes** [remkop/picocli#1204]
Hi, I crated a StackOverflow post [here](https://stackoverflow.com/questions/64205037/set-up-picocli-annotation-processor-in-intellij-maven-project-with-modules)

Basically I want to use the AnnotationProcessor for compile time error checking and use it in IntelliJ. But as soon as I enable the config in the compiler plugin in maven the whole project becomes invalid.

I created a [demo project](https://github.com/hegerdes/PicoCLIsetup) that shows my problem.

All needed Infos should be in there.

**Comment by remkop** [comment]
@hegerdes Thank you for raising this ticket and for providing a sample project. Taking a look...

**Comment by remkop** [comment]
I was able to resolve the problem, but you may not like the solution...

I am guessing that Intelli/J can only handle projects that follow the "standard" Maven project layout, with modules directly under the root project, and modules following the `src/main/java` and `src/test/java` Maven conventions...

When I use the standard layout, remove all Intelli/J files, and re-import the project into Intelli/J, it works as expected.
I get compiler errors if I use for example `@Option` and `@Parameters` on the same field.

I will submit a pull request to the example project, but basically this is the layout that works:

```
$PROJECT
│  pom.xml
│  ReadMe.md
├─core
│  │  pom.xml
│  └─src
│      └─main
│          └─java
│              └─edu
│                  └─bonn
│                      └─cs
│                          └─iv
│                              └─core
│                                  └─config
│                                          Commons_cliTest.java
│                                          ConfigHandler.java
│                                          PicocliTest.java
│
├─src
└─util
    │  pom.xml
    └─src
        └─main
            └─java
                └─edu
                    └─bonn
                        └─cs
                            └─iv
                                └─util
                                        Helper.java
```

**Comment by hegerdes** [comment]
That is exactly what I was afraid of. I copied the structure of project I'm working on and thought that this causes the problem. Unfortunately I'm not in charge of the whole project (If I was I would have changed it immediately, it already caused other problems)

I will discuss this in the team. Either we will refactor the project or probably use a other cli parser. I have no decision-making power there.
But to sum things up, this ended up not being a picocli problem or anything you have control of, right?  Meaning it is all IntelliJ related and might and be fixed somehow with their settings or a patch.

Thank you **A LOT** for this.
You created a very powerful and customizable cli tool that has a lot more to offer that commons-cli or some others.

**Comment by remkop** [comment]
> to sum things up, this ended up not being a picocli problem or anything you have control of, right? Meaning it is all IntelliJ related and might and be fixed somehow with their settings or a patch.

Yes, that is my understanding.  I actually had a bit of a hard time getting it to work even after using the Maven conventional project structure. The existing IntelliJ files somehow retained that `core` was previously located in `../src/core` and it was generating the `.class` files in `../src/core/target`. This meant that I was unable to run `PicocliTest` in IntelliJ (even though `mvn verify` passed successfully).

Only after removing all IntelliJ setting files and re-importing from the `pom.xml` I was able to get things working in IntelliJ.

I am not sure whether the main problem is that the modules are under `src` instead of under the main project, or whether IntelliJ cannot handle modules that do not follow Maven's `src/main/java` convention... You may need to experiment to dig deeper...

> Thank you A LOT for this.
> You created a very powerful and customizable cli tool that has a lot more to offer that commons-cli or some others.

You are welcome! Please star ⭐  picocli on GitHub if you get a chance and enjoy using the project! 😉
