### ISSUE TITLE
default exit from tool that spawns off main thread

### ISSUE THREAD

**Issue by axtimwalde** [remkop/picocli#1216]
I am probably too dense, but I cannot find a solution for his scenario:

I have a GUI tool that spawns a UI thread that runs the entire tool and returns immediately.  With `ComandLine.call(...)` or `CommandLine.run(...)`, the tool would exit when the UI thread dies, i.e. when the main window was closed.  Now that these methods are deprecated, I am using `new CommandLine(new Tool()).execute(args)` which returns an exit code that I should then use in an explicit `System.exit(code)`.  But I cannot yet exit because the actual tool works in this other thread.  I could now add complicated logic to watch the status of this other thread and `System.exit(...)` on it disappearing but I also think that this is clumsy and there must be a better way to simply exit when the main method finishes, is it?  Thanks for any help and for this fabulous library!

**Comment by remkop** [comment]
How about exiting from the UI thread? If this is Swing, you can add something like this to the main window:

```
frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
```

To be honest, I am a bit confused by the bit where you say that 

> With `ComandLine.call(...)` or `CommandLine.run(...)`, the tool would exit when the UI thread dies, i.e. when the main window was closed. 

How are `ComandLine.call` and `run` different from using `CommandLine.execute`? They both just kick off the business logic, which starts the UI in a non-daemon thread, right? So the problem is getting the UI thread to die instead of run forever. I am not sure how the old `ComandLine.run/call` API makes a difference here...

**Comment by remkop** [comment]
...and I am glad to hear you like picocli! 😊 
Don't forget to give the project a star ⭐ on GitHub! 😉

**Comment by axtimwalde** [comment]
You are right!  I updated more than one dependency at a time and it is an issue with the UI part of the app.  Sorry for the noise!

**Comment by axtimwalde** [comment]
Also thanks for the Swing advice, this works for this app and we should make this part of our options https://github.com/bigdataviewer/bigdataviewer-vistools/issues/48

**Comment by remkop** [comment]
No worries!

I saw your mention in the bdv project. 
Glad my suggestion was useful!
