### ISSUE TITLE
Want to be able to parse the flags before instantiating an instance of the (sub)command classes

### ISSUE THREAD

**Issue by nveeser-google** [remkop/picocli#1237]
We use Guice dependency injection everywhere. We also have an internal flag library. 

I can use the IFactory interface (wrapping a Guice Injector) to building of the command classes.
However, there are times when I need the user to specify flags, which are required to initialize Guice, and before I can initialize the command class itself. So I am trying to find a way to parse / process the flags 

It seems that when I parse the flags the command class is initialized (I thought it would be initialized lazily?)

**Comment by remkop** [comment]
If I understand the problem correctly, there is a bit of a chicken-and-egg problem here: you need to parse the command line to configure Guice, and you need a fully configured Guice in order to construct objects during parsing.

One idea is to parse in two separate passes, the first pass to pick up the Guice configuration options, and the second pass to parse the remaining options before running the business logic.

Something like this:

```java
class GuiceConfigurationOptions {
    @Option(names = "--option1") String opt1;
    @Option(names = "--option2") String opt2;
    @Option(names = "--option3") String opt3;
    @Unmatched List<String> ignored;
}
```

Use the above to extract the Guice configuration options from the command line args.
This is the first pass:

```java
GuiceConfigurationOptions guiceConfig = CommandLine.populateCommand(new GuiceConfigurationOptions(), args);
```

Now that you have the configuration, you can configure Guice and parse the command line args again.
This is the second pass:
```java
MyGuiceFactory factory = new MyGuiceFactory(guiceConfig);
int exitCode = new CommandLine(MyApp.class, factory).execute(args);
```

Putting it all together:

```java
class MyApp implements Runnable {
    @Option(names = "-x") int x; // example options used in the business logic
    @Option(names = "-y") int y;

    @Mixin GuiceConfigurationOptions ignored; // so that the parser will not complain about unknown options

    public void run() { ... } // your business logic

    public static void main(String... args) {
        // pass 1
        GuiceConfigurationOptions guiceConfig = CommandLine.populateCommand(new GuiceConfigurationOptions(), args);
        MyGuiceFactory factory = new MyGuiceFactory(guiceConfig);

        // pass 2
        int exitCode = new CommandLine(MyApp.class, factory).execute(args);
        //System.exit(exitCode);
    }
}
```

Does that answer your question?

**Comment by nveeser-google** [comment]
That actually clarifies.
I think my request is in two parts

Part one is using the flags to configure Guice. I had a separate solution for that but your solution above it probably clearer.

Part two is that I want inspect subcommand that will be run to influence the configuration as well. This will allow each subcommand to define it's own Guice context if possible?

I need to fine the class that will be invoked, but without constructing it. That might be a step too far...;)

```java
@Command(name = "run-stuff")
class SubCommand implements Runnable {

    @ModuleFactory
    public static Module module() {
       ...
   } 
}
```

**Comment by remkop** [comment]
> Part two is that I want inspect subcommand that will be run to influence the configuration as well. This will allow each subcommand to define it's own Guice context if possible?

I see. Is it not possible to create Guice contexts for all subcommands up front and put them in the factory?

If each subcommand has its own separate Guice config that is customizable via the command line, you may be able to do this by changing the first pass a little bit, like this:

```java
MyApp app = new MyApp();
ParseResult parseResult = new CommandLine(app).parseArgs(args); // just parse (without factory), don't run biz logic

GuiceConfigurationOptions guiceConfig = app.getGuiceConfig();
MyGuiceFactory factory = new MyGuiceFactory(guiceConfig);
```

You can now inspect the `ParseResult` to find out which subcommands were specified on the command line, something like this:

```java
if (parseResult.hasSubcommand()) {
    ParseResult subResult = parseResult.subcommand();
    if (subResult.commandSpec().name().equals("run-stuff")) {
        SubCommand sub = subResult.commandSpec().userObject();
        SubGuiceConfig subConfig = sub.getGuiceConfig();
        factory.addConfig(SubCommand.class, subConfig); // something like this?
    }
}
```

> I need to find the class that will be invoked, but without constructing it. (...)

During the first pass, subcommands may be constructed, but that should not be a problem since you are not executing the business logic. Picocli will construct subcommand objects when they are specified on the command line. The idea of parsing in 2 passes is that during the 1st pass, those objects are constructed in order to collect configuration values from the command line.

During the next pass, subcommands will be constructed again, but this time with the proper Guice configuration so now you can run the business logic.

Does that allow you to make progress?

**Comment by remkop** [comment]
@nveeser-google Did this answer your question, and can this ticket be closed? Feel free to ask if is there something that still needs follow-up.

**Comment by nveeser-google** [comment]
So my take away is that by definition I cannot parse the args without instantiating the userObject (when its a class).

For #1 I can parse the flags ahead of time and pull out the flags that are required for guice ahead of time

For #2 I can probably mess with the IFactory implementation to initialize the injector from the class static method before injecting it.

That likely works.

**Comment by remkop** [comment]
This was not an easy one. 
Glad to hear you got something working for you!

Don’t forget to star picocli on GitHub if you like the project. 😉
