### ISSUE TITLE
Enum as option

### ISSUE THREAD

**Issue by xenoterracide** [remkop/picocli#1278]
ok, so I have this

```java  
@CommandLine.Option(
    names = { "--level"},
    defaultValue = "error",
    showDefaultValue = CommandLine.Help.Visibility.ALWAYS,
    description = "enable debug logging"
  )
  private Level logLevel = Level.ERROR;
```
which doesn't work because apparently Level is a class and not an enum, wtf log4j. However, I think it would be cool if (if this was an enum).

if you could do this

```java  
@CommandLine.Option(
    names = { "--level"},
    defaultValue = "error",
    showDefaultValue = CommandLine.Help.Visibility.ALWAYS,
    description = "enable debug logging",
    enumAsOptions = true
  )
  private Level logLevel = Level.ERROR;
```

and what it would do is generate `--debug` `--warn` `--error` etc, as mutually exclusive options.

**Comment by remkop** [comment]
Interesting! (I know some of the background of why `Level` is not an enum; long story short, this allows for user-defined `Levels`.)

Interesting idea. Will you be able to provide a pull request for this? I can help a bit but my time is very limited.

**Comment by remkop** [comment]
@xenoterracide I have put some thought into this, let me share what I came up with:

# Auto-generating options from an Enum

There are multiple aspects to this, exploring some of them below. (Thinking out loud...)

## Option names

The idea is that applications declare this option once, and the library would automatically generate the option names for this option, based on the enum values.  

### Configurable name mapping

There would need to be some mapping between enum values and option names, a straightforward way to do this would be something like `optionName = "--" + enumValue.name().toLowerCase()`. I imagine that this mapping would need to be configurable so that applications can define their own mapping, perhaps to generate both short option names and long names (`-o` as well as `--option`), or get the option name from something else than `Enum.name()`.

### Parser

Adding auto-generated names to the set of option names for a command may be relatively straightforward. The picocli parser does something similar with [negatable options](https://picocli.info/#_negatable_options). Unclear whether additional bookkeeping will be required.

### Usage help

How to display these auto-generated options in the usage help message? Simply list all supported option names, with the same `description` (so the description is shown multiple times, once for each enum value)? What if the enum has many values?

I suspect that a common requirement will be the ability to group such options together, rather than display them alphabetically, mixed in the full list of all the other options. If so, how would this grouping work? Perhaps it needs its own header? Perhaps we want the ability to show the description only once for all option names in this group?

Many questions here...

## Capturing user-specified values

I am assuming that these auto-generated options would work like boolean flags, so generate `--debug`, `--warn`, `--error` etc. as options that do not take a parameter. (If that assumption is incorrect things get more complicated because then we need a place to store the specified enum as well as a place to store the specified value associated with that enum value.)

This allows us to have an annotated field that has the enum as its type, and the parser sets that field to the enum value associated with the specified option name.

For some use cases, like the log level example, having a single value makes the most sense, but I imagine there can be other use cases where end users can select a subset of available values. For example: an enum of supported programming languages, and the end user specifies `--java`, `--groovy` and `--scala`, and the application generates some code in the specified languages. So, we may want to support multiple values.

One idea is to control that with the type, so a single enum would make the auto-generated options mutually exclusive, while an `EnumSet` would allow multiple values to be captured.

# Custom solution

By using [argument groups](https://picocli.info/#_argument_groups), applications can already achieve all the above requirements with the current version of picocli, without additional library support. For example, the logging options use case could look like this:

```java
public class CustomEnumOption implements Runnable {
    static class LogLevel {
        enum TheEnum { debug, info, warn }

        TheEnum actualValue = TheEnum.warn;

        @Option(names = "--debug", description = "Sets log level to DEBUG.")
        void setDebug(boolean value) {
            actualValue = TheEnum.debug;
        }

        @Option(names = "--info", description = "Sets log level to INFO.")
        void setInfo(boolean value) {
            actualValue = TheEnum.info;
        }

        @Option(names = "--warn", description = "Sets log level to WARN.")
        void setWarn(boolean value) {
            actualValue = TheEnum.warn;
        }
    }

    @ArgGroup(exclusive = true, heading = "Log Level Options%n", multiplicity = "0..1")
    LogLevel logLevel = new LogLevel();

    @Option(names = "--option", description = "Some other option")
    String value;

    @Override
    public void run() {
        System.out.printf("The log level is %s%n", logLevel.actualValue);
    }

    public static void main(String[] args) {
        new CommandLine(new CustomEnumOption()).execute(args);
    }
}
```

The usage help for the above example looks like this:

```
Usage: <main class> [--option=<value>] [--debug | --info | --warn]
      --option=<value>   Some other option
Log Level Options
      --debug            Sets log level to DEBUG.
      --info             Sets log level to INFO.
      --warn             Sets log level to WARN.
```

# Trade-offs

Advantages of the custom solution using argument groups:

* control over the usage help message
* support for grouping with header in the usage help
* each option can have their own description
* already available: implemented and documented

Advantages of library support

* User code would be smaller, more terse
* (other?)

# Conclusion

Using argument groups solves all the issues and answers all the questions that I could think of. If we were to support auto-generating options from an enum, we would need to design, develop, test, document and support an alternative implementation that delivers the exact same functionality that already exists with argument groups.

The benefit of smaller user code may rapidly vanish when an application wants fine-grained control over how option names are mapped from enum values or how the usage help message appears. The resulting application code may be just as large as with argument groups.

It looks like not adding library support is the best way.

Thoughts?

**Comment by xenoterracide** [comment]
> The benefit of smaller user code may rapidly vanish when an application wants fine-grained control over how option names are mapped from enum values or how the usage help message appears.

it's for simplistic mapping, if you need to get complicated there are obviously better options

> The resulting application code may be just as large as with argument groups.

personally, meh, application code size doesn't matter to me when using the JVM. Pretty certain even the most trimmed down JVM is "huge".

**Comment by remkop** [comment]
It was an interesting idea, and worth thinking it through!

My conclusion is that it’s not that much work for applications to create an argument group for this. I feel that the benefits of supporting this in the library are limited. 

Closing this for now. We can reopen if new arguments come up.
