### ISSUE TITLE
How to evaluate a specific option before any other option

### ISSUE THREAD

**Issue by sebthom** [remkop/picocli#1295]
I created an abstract command that defines an option `--log-file` which when specified will write all output to the given log file. When set a java util logging file appender will be configured.

Is it possible that picocli evaluates this option before any other option - no matter the order specified in the command line? This is to ensure that all errors/warnings etc created by other options are also written to the specified logfile. Currently I am using this workaround:

```java
public abstract class AbstractCommand implements Callable<Void> {
   @Option(names = "--log-file", description = "Write console output also to the given log file..")
   private void setLogFile(@SuppressWarnings("unused") final Path path) {
      // nothing to do, already handled in main
   }
}

@Command(name = "mycommand")
public class MyCommandMain extends AbstractCommand {

   public static void main(String[] args) throws Exception {

      // this is a hack, but we need to evaluate this option before
      // any other component starts logging/throwing exceptions
      var logFilePos = 1 + ArrayUtils.indexOf(args, "--log-file");
      if (logFilePos > 0 && logFilePos < args.length) {
         var logFilePath = args[logFilePos];
         JdkLoggingUtils.addFileHandler(logFilePath);
      }

      var handler = new CommandLine(new MyCommandMain());
      handler.setExecutionStrategy(new RunLast());
      // ...
  }

  // ...

}
```

**Comment by remkop** [comment]
Hi @sebthom!
Picocli evaluates options in the order that they are specified on the command line. This is not easy to change.

What I recommend for cases like this is a 2-pass parsing approach, similar to what you are already doing in `main`.

However, instead of parsing the args yourself, and perhaps missing things like `--log-file=/some/path`, or quoted values, etc, why not use picocli for the first pass as well, by calling [`CommandLine.parseArgs`](https://picocli.info/apidocs/picocli/CommandLine.html#parseArgs-java.lang.String...-) or [`CommandLine.populateCommand`](https://picocli.info/apidocs/picocli/CommandLine.html#populateCommand-T-java.lang.String...-)? Perhaps something like this?

```java
class LogFile {
    @Option(names = "--log-file")
    public Path path;

    @Unmatched List<String> ignored;
}

@Command(name = "mycommand")
public class MyCommandMain extends AbstractCommand {

   public static void main(String[] args) throws Exception {

      LogFile logFile = CommandLine.populateCommand(new LogFile(), args); // terser than parseArgs method
      if (logFile.path != null) {
          JdkLoggingUtils.addFileHandler(logFile.path); // we could even move this to a setter method in LogFile
      }

      var handler = new CommandLine(new MyCommandMain());
      handler.setExecutionStrategy(new RunLast());
      // ...
  }
```

**Comment by sebthom** [comment]
Thanks, that works perfect!

FYI I am using picocli in this project https://github.com/vegardit/copycat

**Comment by remkop** [comment]
Copycat looks pretty awesome!
Enjoy!
