### ISSUE TITLE
IllegalAccessError on inner class CommandLine.Model.ArgSpec.Builder

### ISSUE THREAD

**Issue by aappddeevv** [remkop/picocli#1333]
I'm not quite sure the circumstances yet but I'm getting a runtime IllegalAccessException on CommandLine.Model.ArgSpec.Builder when creating an instance of a subclass.

The static, abstract superclass is not marked public but the subclasses, e.g. PositionalParamSpec.Builder, are.

I was able to resolve the access issue by adding `protected` to the class modifiers on ArgSpec.Builder.

I'll try to find out the issue and where it is specific to my compiler.

**Comment by remkop** [comment]
Thank you for raising this. 

Can you provide more detail?
I assume you are using the programmatic API, not the annotations API. 
Are you creating a custom subclass of ArgSpec.Builder, or does the error happen when calling `build()` on the built-in subclasses like OptionSpec.Builder?

You mention the compiler, are you using something other than the OpenJDK?

Can you show some sample code or point to a sample project that reproduces the issue?

**Comment by aappddeevv** [comment]
I've not been able to probe deeper. I tried it on a variety of java 1.9+ VMs. It was the programmatic API. No subclasses. It appears to happen when calling `.build()` on the built-in subclasses. I'll try to create a minimized example. I'm running on scala3 M3 but I've not seen this error before. It is unrelated to modules. I think I added `public` not `protected`.

It only happens when adding a `converter(myconverter)` instance. Everything else around the option builders seem to work fine otherwise. With the change, everything else has been working.

**Comment by remkop** [comment]
I see, so this is happening when using the programmatic API in a Scala program? Interesting!

Can you provide a small program that reproduces the issue? That will help me investigate.

**Comment by aappddeevv** [comment]
Let me keep using it for a bit more to see if I hit the access issue again on other parts. So far I have not though. It's literally only when using `.converters` which seems really, really strange. 

I think that having the base class marked public is good for other reasons such as creating DSLs for common methods across the subclasses. Otherwise, its doubles the DSL work because you can't pick off the base class common methods.

**Comment by remkop** [comment]
Can you provide at least a stacktrace?

**Comment by aappddeevv** [comment]
I cannot. I cannot compile my app now without the public modifier and this was a runtime error.

Let me do some upgrade of the compiler and see if that helps and its a compiler issue. May take a week or so.

However, I think being able to attach a DSL to the base class is probably enough motivation to suggest that it be made public.

**Comment by remkop** [comment]
Okay. I have to confess it's a bit hard for me to follow what is going on. :-)
So, the project you are working on is using Scala, and I gather you are building a DSL that uses the picocli programmatic API.

You mentioned that initially you encountered a runtime `IllegalAccessException` on `CommandLine.Model.ArgSpec.Builder` when creating an instance of a subclass. Currently you are seeing a compilation error. So, something else must have changed other than changing the visibility of `ArgSpec.Builder` from `protected` to `public`.  I am guessing the compilation error is in the DSL project that has your modified version of picocli as a dependency.

If the `protected` to `public` change is the only change, you can revert to depending on picocli 4.6.1 from Maven instead of your modified version of picocli. Have you tried that?

If you have made multiple changes to picocli, we may need to retrace them one by one. Have you cloned or forked the picocli project so you can retrace your changes? If you haven't, it may be worth starting by forking and systematically making small changes one at a time to see what happens.

**Comment by aappddeevv** [comment]
I just copied the entire 1 file library (1 file really made it easy), and changed the modifier.

The compilation error is due to the fact that I use the DSL now. I'd have to rip it out to run with the standard picocli library so I could not just swap in the other picocli library. Without the public modifier I cannot target the base class since it is not visible. The public modifier to solve the IllegalAccessException is a different issue than the public modifier to target the base class for extension methods, however, the public modifier solves both issues.

No other changes.

**Comment by remkop** [comment]
Hi @aappddeevv, how have things been going with this issue?

**Comment by remkop** [comment]
Hi @aappddeevv can you give an update on where you are with this issue?
For me to consider changing the modifier for `ArgSpec.Builder` to `public` I need to understand why this is necessary.
(If you have moved on to something else, that is fine, please let me know or go ahead and close this ticket.)

**Comment by aappddeevv** [comment]
Been buried. The only reason to expose these as public would be to allow other languages such as kotlin or scala to be able to extend them, at that level of class definition, with new methods for convenience and better integration into kotlin or scala idioms.
