### ISSUE TITLE
Support for progressbar for CLI

### ISSUE THREAD

**Issue by kaushalkumar** [remkop/picocli#1354]
Hi - Does picocli support any feature of progress bar? I could not locate it in the doc, can you please check and help us with this. If there is no such support then do let us know if it could be included in future.
Need - At times CLI takes time to execute a command and user has no clue on progress. displaying progress is first step to keep the user acknowledged. Second step could be to provide an estimated remaining time. 

We found a lib https://github.com/ctongfei/progressbar on github, but were thinking if picocli can provide any such feature.

**Comment by remkop** [comment]
Hi @kaushalkumar!
Thanks for providing that link! That looks like a pretty cool library!

I doubt I'll be able to do better than @ctongfei :-)

From what I can see, ctongfei/progressbar can be used from the run or call method of a picocli command without any problem so that seems the easiest thing to do for everyone. 

I'm thinking to link to their work from the picocli manual.

**Comment by kaushalkumar** [comment]
Hey - Thanks for quick reply. One thing to keep in mind while using such feature will be around correct estimation of time (specifically remaining time).
I think progress in terms of tasks(completed vs remaining) is easier than progress in terms of time. Cheers

Closing this ticket
