### ISSUE TITLE
Usage duplication with ArgGroup and array with arity 1..2

### ISSUE THREAD

**Issue by albertus82** [remkop/picocli#1418]
Hello, I'm experiencing a curious behaviour of the help when using `@ArgGroup`.

I have three mutually exclusive options, so I defined a group as you can see in the following example:

```java
@Command(name = "groupexample", mixinStandardHelpOptions = true)
public class GroupExample implements Callable<Integer> {

	@Parameters(index = "0", description = "Mandatory parameter.")
	private String param1;

	@ArgGroup(exclusive = true, multiplicity = "1")
	private Dependent group;

	private static class Dependent {
		@Parameters(index = "1", arity = "0..1", paramLabel = "<text>", description = "Input text from command line.")
		private String inputAsArg;

		@Option(names = { "-i", "--interactive" }, interactive = true, echo = false, description = "Ask input text interactively.")
		private String inputInteractive;

		@Option(names = { "-f", "--file" }, arity = "1..2", paramLabel = "<file>", description = "Input and optional output file (default output to stdout).")
		private File[] files;
	}

	public static void main(final String... args) {
		System.exit(new CommandLine(new GroupExample()).execute(args));
	}

	@Override
	public Integer call() {
		return ExitCode.OK;
	}
}
```

The autogenerated help is:

```
Usage: groupexample [-hV] ([<text>] | -i | -f=<file> [<file>] [-f=<file>
                    [<file>]]...) <param1>
      <param1>        Mandatory parameter.
      [<text>]        Input text from command line.
  -f, --file=<file> [<file>]
                      Input and optional output file (default output to stdout).
  -h, --help          Show this help message and exit.
  -i, --interactive   Ask input text interactively.
  -V, --version       Print version information and exit.
```

As you can see, in the usage the `-f` option is duplicated. If I remove the `@ArgGroup`, this duplication does not occur.

There are other two things that I did not understand: the first is the meaning of the ellipsis after the usage help of `-f`, that is present either with or without the group. The second one is how to customize the `paramLabel` of the up-to-two values that follow the `-f` option, because the application expects one or two files after `-f`: the first is the input file, mandatory, and the second is an optional output file (arity 1..2), so I would prefer something like  `-f, --file=<input_file> [<output_file>]`.

Thank you a lot for your great work.

**Comment by remkop** [comment]
There are two things to notice about the `-f` option:
* First, values are captured in a multi-value data structure (an array of `File` objects). This means that the `-f` option can be specified multiple times, so the following is valid input: `-f=a -f=b -f=c`, resulting in three `File` objects in the array. To express this, the synopsis shows `-f <a> [-f <a>]…`. The ellipsis means that the `-f` option can be specified any number of times. 
* Secondly, the `-f` option has `arity = 1..2`. This means that the `-f` option takes at least one and at most two parameters. 

The `paramLabel` attribute can be used to control the name of the option parameter in the synopsis. The `hideParamSyntax` attribute can be used to hide the decorations like `[` and `]…`

However, I recommend that you have a separate option for the second (output) file instead. 
So instead of an array, have an option `-f` of type `File`, and a second option `-o` also of type `File`.  You can put those two options in a non-exclusive ArgGroup where the `-f` option is required and the `-o` option is not required. 

I believe that expresses the semantics of what you’re trying to achieve better, and is also easier to understand for your end users.

**Comment by albertus82** [comment]
Thank you again, @remkop, probably I'll rethink the semantics.

I still don't understand why, without using the ArgGroup, a single occurrence of `-f=<file> [<file>]` is printed (which I think it's right, unlike the usage line printed using group - see the original post):

```java
@Parameters(index = "0", description = "Mandatory parameter.")
private String param1;

// @ArgGroup(exclusive = true, multiplicity = "1")
// private Dependent group;

// private static class Dependent {
@Parameters(index = "1", arity = "0..1", paramLabel = "<text>", description = "Input text from command line.")
private String inputAsArg;

@Option(names = { "-i", "--interactive" }, interactive = true, echo = false, description = "Ask input text interactively.")
private String inputInteractive;

@Option(names = { "-f", "--file" }, arity = "1..2", paramLabel = "<file>", description = "Input and optional output file (default output to stdout).")
private File[] files;
// }

```
Output (right IMHO):
```
Usage: groupexample [-hV] [-i] [-f=<file> [<file>]]... <param1> [<text>]
```

**Comment by remkop** [comment]
Looking at your output, I see this:

```
[-f=<file> [<file>]]...
```

not what you said: `-f=<file> [<file>]`. 

This is what I would expect: `[-f=<file> [<file>]]...`: before you’re using an array, the `-f` option is multi-value and can be specified zero or more times, each time with one or two parameters. 

I don’t see any problem.

**Comment by albertus82** [comment]
Thank you again @remkop, obviously I was missing something.
