### ISSUE TITLE
IExecutionStrategy doc references deprecated CommandLine.execute

### ISSUE THREAD

**Issue by gadeweever** [remkop/picocli#1421]
Section https://picocli.info/#_initialization_before_execution uses deprecated invocation in `return new CommandLine.RunLast().execute(parseResult);`. 

What is the recommended usage for `IExecutionStrategy`? Additionally the docs should be updated to include the recommended usage.

**Comment by remkop** [comment]
Hey you are right! I never noticed that. Thanks for raising that.

It was not my intention to deprecate the `execute` method, to the contrary, that is the recommended method to use. 

I think it became this way because I deprecated `AbstractParseResultHandler` (the superclass of `RunLast`), where the `execute` method is implemented.

The fix is to override the `execute` method in the subclasses of `AbstractParseResultHandler`:

```java
        /** {@inheritDoc} */
        public int execute(ParseResult parseResult) throws ExecutionException { return super.execute(parseResult); }
```

This will be part of the next release.
