### ISSUE TITLE
Compile error with picocli-shell-jline3 and java modules

### ISSUE THREAD

**Issue by StephanStofer** [remkop/picocli#1452]
I recently posted a question on [stackoverflow](https://stackoverflow.com/questions/69688720/using-picocli-with-picocli-shell-jline3-and-configured-java-modules-leads-to-unn) regarding java modules with picocli. 

As I already read your FAQ, I believe the cause is Jline instead of picocli and I should report the issue there?

**Comment by remkop** [comment]
Hi @StephanStofer,
Yes, looking at the Stackoverflow question and comment by Naman, the problem seems to be with JLine.
It is best to raise an issue in the JLine project.

I haven't checked, but the JLine jar files may not be module-compliant: if multiple jar files contain classes with the same package, that causes problems: such jars cannot be used together. (https://stackoverflow.com/questions/40985153/with-java-9-modules-will-multiple-modules-be-able-to-export-the-same-package)

**Comment by StephanStofer** [comment]
@remkop thanks for your reply, I will raise an issue in the JLine project.

**Comment by remkop** [comment]
@StephanStofer Are there any follow-up questions, or can this ticket be closed?

**Comment by StephanStofer** [comment]
Yep, thanks for your help.
