### ISSUE TITLE
Autocompletion doesn't display completion candidates on exact match

### ISSUE THREAD

**Issue by rsenden** [remkop/picocli#1468]
Given a subcommand structure like the following:
- `mycmd`
     - `abc`
     - `abcdef`
           - `sub1`
           - `sub2`

There are two issues with the autocompletion script generated by picocli v4.6.2:
- `mycmd abc<TAB><TAB>` doesn't display any completion candidates
     - Expected: Display completion candidates: `abc` and `abcdef`
- `mycmd abcdef<TAB><TAB>` doesn't display any completion candidates
     - Expected: Insert a space and display completion candidates `sub1` and `sub2`

I've had a look at the generated completion script, but given my limited experience with autocomplete scripts I'm not sure how this can be fixed.

**Comment by remkop** [comment]
Thank you for raising this! This is now fixed in master and will be included in the next release.

The cause was that on `mycmd abc<TAB><TAB>`, the completion script jumps to the `_picocli_mycmd_abc` function, whereas the desired completion behaviour comes from invoking the `_picocli_mycmd` function. I updated the autocompletion generator to cater for this special case of an exact match.

Thanks for the example, it was very useful. For reference, I used the following program to match your use case:

```java
@Command(name = "mycmd", mixinStandardHelpOptions = true,
    subcommands = {
        Issue1468.Abc.class,
        Issue1468.Abcdef.class,
        AutoComplete.GenerateCompletion.class})
public class Issue1468 {
    @Command(name = "abc", mixinStandardHelpOptions = true)
    static class Abc {}

    @Command(name = "abcdef", mixinStandardHelpOptions = true)
    static class Abcdef {

        @Command(mixinStandardHelpOptions = true)
        void sub1() {}

        @Command
        void sub2() {}
    }

    public static void main(String[] args) {
        new CommandLine(new Issue1468()).execute("generate-completion");
    }
}
```
