### ISSUE TITLE
Annotation way to represent subcommands

### ISSUE THREAD

**Issue by nagkumar** [remkop/picocli#152]
It would be easy to make commands represented  as subcommands through annotation rather than api way

Currently one needs to use addSubcommand api.

**Comment by kakawait** [comment]
What I did for _Picocli Spring boot starter_ was to keep `@Command` annotation but using _static nested_ class hierarchy to determine _subcommand_ https://github.com/kakawait/picocli-spring-boot-starter

**Comment by remkop** [comment]
I'm thinking to address this by adding a `subcommands` attribute to the `@Command` annotation.

Defining a subcommand hierarchy would look like this:

```
@Command(subcommands = {
    Capacity.class,
    Park.class,
    Leave.class,
    Status.class,
    Query.class,
    Exit.class })
class MainCommand { }
```
By calling `new CommandLine(new MainCommand())`, the declared subcommands are automatically instantiated and added to the CommandLine instance. When the `subcommands` annotation attribute is present there is no need to call `CommandLine::addSubcommand`. 

Picocli will throw an exception when subcommands referenced in a `subcommands` attribute do not have a `@Command` annotation with a `name` attribute. This name will be used both for parsing and for generating usage help. 

To parse the command line, use the `CommandLine::parse` method (the `populateCommand` method does not work for subcommands):
```
// application class
public static void main(String[] args) {
    List<CommandLine> parsedCommands = new CommandLine(new MainCommand()).parse(args);
    // do something
```

Thoughts?

**Comment by nagkumar** [comment]
proposed subcommand attribute,  to take array of classes is too good.

Not sure why populate command should not work for sub commands. It can continue to work the way it is i.e. if   developer gives right command and args it would populate it as it is now.

**Comment by remkop** [comment]
I hope that "too good" means you like it. :-)

`populateCommand` doesn't work well with subcommands because you pass in a domain object and the command line args, and you get back that same domain object. 

The problem is that there's no reference to the subcommands. The method doesn't return a list. Also, it doesn't return a `CommandLine` instance that you could query for subcommands. That's why the `parse` method is more appropriate for subcommands.

**Comment by nagkumar** [comment]
Truly it is good, as I was thinking just opposite.. i.e. let `sub-sub-`command have a way to reference its parent, some thing as below
```
@Command(parent=MainCommand.class)
class Capacity(){
}
```

**Comment by remkop** [comment]
Ok, glad you like it. 

To be honest, I would not know how to implement this the other way around because it requires the parent to dynamically discover all classes annotated with `@Command` which is not easy.

The above I have a clear idea on how to implement and how it could be useful elsewhere (for #121  in particular.)

**Comment by nagkumar** [comment]
What you proposed can also help in a case, where same sub-command say `Capacity `can be part of two or more main commands i.e for both 

`Main1Command() `and `Main2Command()` too.

**Comment by remkop** [comment]
Yes, that was another consideration.

**Comment by nagkumar** [comment]
> To be honest, I would not know how to implement this the other way around (subcommands knowing about their parent) because it requires the parent to dynamically discover all classes annotated with @Command that they are mentioned in which is not easy.

I have not tried, but the solution is here, specially classindex

https://stackoverflow.com/questions/259140/scanning-java-annotations-at-runtime
https://github.com/atteo/classindex
