### ISSUE TITLE
Signature change for CommandLine.populateCommand() and new CommandLine() 

### ISSUE THREAD

**Issue by nagkumar** [remkop/picocli#155]
both CommandLine.populateCommand() and new CommandLine() expects user to pass which command object against which parsing of the arguments to be done.

 In reality, when program is launched with CLI commands, program is not sure what command user is asking to be executed..

This can be big if condition to identify which command object could that be..to satisfy populateCommand and new  CommandLine() call, better this can be avoid..

Currently, to overcome this, I am creating a Virtual command, with all the commands as subcommands and parsing.

**Comment by remkop** [comment]
What you are currently doing (what you call a virtual command) is the correct way to deal with this.

Your java program will be invoked in one of the following ways:

1. `java -cp somejar.jar com.yourproject.YourMainClass -option=value subcommand -option2=value2 etc`

1. `java -jar someExecutable.jar -option=value subcommand -option2=value2 etc`

1. `wrapperscript -option=value subcommand -option2=value2 etc`

Note that the top-level command at the top of the CommandLine hierarchy does not actually appear on the command line. Only subcommand(s) appear on the command line. So in a way picocli gives you a virtual command already. The `@Command(name="commandname")` for the top-level command is mostly for the usage help message, rather than for parsing.

**Comment by nagkumar** [comment]
_java -cp somejar.jar com.yourproject.YourMainClass -option=value subcommand1 -option2=value2 etc
java -jar someExecutable.jar -option=value subcommand2  -option2=value2 etc
wrapperscript -option=value subcommand3  -option2=value2 etc_

In above 3 commands, how to use the api  populateCommand() and new CommandLine() 
as one of the parameter these api takes is exact sub-command to be passed. However, when main method is invoked, it could be subcommand1 or subcommand2 etc..

**Comment by nagkumar** [comment]
>Only subcommand(s) appear on the command line.

If that is the case, any reason to name the annotation a @Command..instead of @SubCommand

The way I understand sub-command is , say in eg.

`hadoop fs –help ls`

in this fs is command, ls is sub command, this ls is valid subcommand of fs and not for hadoop version similarly 

in 

`hadoop fs –help mkdir `

fs is main command, mkdir is sub command

more details on hadoop command line as example are 

https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/CommandsManual.html

**Comment by remkop** [comment]
In my understanding `hadoop` is the command, and `fs` is the subcommand, and `ls` and `mkdir` are sub-subcommands. This is similar to `git`. 

The wrapper script name or the main class name could be considered the command name, but as you know, in java it is not part of the command line arguments, so they are not relevant for parsing purposes. I guess this is a quirk of Java.

**Comment by remkop** [comment]
I get the impression that this question is a different way to phrase the question under #156. Did my answers clear up things for you?

**Comment by nagkumar** [comment]
Your info did give me good clarity that everything can be treated as sub command at main level, however, my question still remains, when the main method is called, how to avoid long if condition to know what command is called.. to invoke populateCommand command. Wish that logic gets handled by this framework.

That, can we add new api or modify existing, so that, one can blindly pass all the arg to this cli framework and it can best job of matching the which Command user is invoking based on the knowledge it has of all the @Command(s) defined.

**Comment by remkop** [comment]
Thanks for following up. I think I finally understand. Let's walk through this example:

Suppose you designed your application to have a command hierarchy that looks like this:
```
parking 
|
+- enter
|
+- exit
|
+- admin 
    |
    +- query -usage -exceedingTimeLimit
    |
    +- open 
    |
    +- close
```
One way to implement this design could look like this:
```
// class Parking
public static void main(String[] args) {
  CommandLine application = new CommandLine(new Parking())
    .addSubcommand(new Enter())
    .addSubcommand(new Exit())
    .addSubcommand(new CommandLine(new Admin())
        .addSubcommand(new Query())
        .addSubcommand(new Open())
        .addSubcommand(new Close())
       )
    );

  // now parse the command line 
  List<CommandLine> parsedCommands = application.parse(args);

  // often you are interested in the last 
  // (most deeply nested) subcommand 
  CommandLine deepest = parsedCommands.get(parsedCommands.size() -1);

  // the following is application-specific, but let's assume that
  // every subcommand implements Runnable 
  Runnable subcommand = (Runnable) deepest.getCommand();
  subcommand.run();
} // end main
```

**Comment by nagkumar** [comment]
Very close.. except that, I have many root level commands

enter carNumber
exit  slot
pay amount
query color

This way, when user call main method he can say

java <classnameofmain> <enter >| <exit>... etc..

This in main method, I first need to find out which command user is trying to invoking.
Yes, I can do this with virtual command as Parking and making all of them as subcommands, however, it would be nice, if we have some api to deal with it directly, such as

CommandLine cmd = CommandLine.findAndParse(args);

**Comment by remkop** [comment]
Do you have a separate Java class (with a static main method) for each root level command?

That is, do you run your commands like this?
```
java -cp myApp.jar com.nagkumar.parking.Enter 213
java -cp myApp.jar com.nagkumar.parking.Exit 999888
java -cp myApp.jar com.nagkumar.parking.Pay 50.0
java -cp myApp.jar com.nagkumar.parking.Query blue
````

**Comment by nagkumar** [comment]
exactly, I have one jar with many commands in it however I have only one main class and that main method is not in any of the commands.

Above case my side is

java -cp myApp.jar com.teja.Application create_parking 213
java -cp myApp.jar com.teja.Application park car white ka05ma2456
java -cp myApp.jar com.teja.Application leave 4
java -cp myApp.jar com.teja.Application status

This way, only when one main method exists, I am unable to know which command is being invoked.. hence was looking for some form of api, which can give me best matching command line given just arguments.

**Comment by remkop** [comment]
I must be missing something, because I still don't see why the current API does not work for you. It seems very natural to me to create a virtual command encompassing all subcommands. In fact, I don't see how one could do without it...

I understand you want to be able to blindly pass the command line arguments, and I agree. That is exactly why there needs to be a single top-level CommandLine instance that has the full hierarchy of subcommands. This allows you to just pass the command line arguments array to the `parse` method and let picocli do the hard work of figuring out which subcommands were invoked (see the example above).

The application is a set of subcommands (and potentially nested sub-sub commands). This subcommand hierarchy needs to be defined somewhere anyway, why not use the picocli API? 

Is there something that prevents you from defining the hierarchy of subcommands in a single top-level CommandLine instance? Or, assuming that you use this recommended approach (define the full hierarchy of subcommands in a single top-level CommandLine instance - the virtual command), is there some use case that you cannot accomplish with this?

**Comment by nagkumar** [comment]
>

>virtual command encompassing all subcommands
Advantage of api abstracting this is to avoid the boiler place code which can avoid few bugs, as one needs to remember to add the subcommands.. whenever they get added..

**Comment by remkop** [comment]
I guess what you are referring to is your suggestion in #152 to register subcommands via annotations to replace code like the below. 

```
  CommandLine application = new CommandLine(new Application())
    .addSubcommand(new Enter())
    .addSubcommand(new Exit())
    .addSubcommand(new CommandLine(new Admin())
        .addSubcommand(new QueryStatus())
        .addSubcommand(new CreateParking())
        .addSubcommand(new CloseParking())
       )
    );
```

I am actually reasonably happy with the current API. I like that there is a single unambiguous place where the command hierarchy is defined. The code is reasonably compact; I would not describe the above as boiler plate code, but perhaps others think differently. 

I will give your proposal on #152 more thought. Meanwhile, can this issue be closed?

**Comment by nagkumar** [comment]
Sure. We can close this. It has conveyed what i am looking for.
