### ISSUE TITLE
Add support for option modifiers

### ISSUE THREAD

**Issue by SagaciousZed** [remkop/picocli#176]
The programmer can enable modifiers for options which changes how the cli interprets the value for the option. Inspired by the [Java Keytool](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/keytool.html#keytool_option_storepasswd)

For example:
`-option value` would use the _value_ directly for _option_.
`-option:env value` would treat _value_ as a environment variable to look up for the actual value to supply to _option_.
`-option:file value` would treat _value_ as a path to a file to read for the value supplied to _option_

Useful for application wishing to hide sensitive information, such as passwords, from the command line.

**Comment by remkop** [comment]
Interesting idea!

It reminds me a little of Log4j2's [Lookups](https://logging.apache.org/log4j/2.x/manual/lookups.html), where one can specify `${sys:key}` to get the value from a system property, `${env:key}` to get the value from an environment variable, etc. Maybe we can do something similar for passwords. 

Thoughts?

**Comment by SagaciousZed** [comment]
From a interaction standpoint, I don't quite agree, with trying the password prompt behind a option modifier. Keytool will prompt for passwords on the console when the options are not passed, and I think the same behavior exists for openssl. On the other, hand there are some shell like programs, like mongo and mysql which require a the password flag to have no arg given to prompt for a password.

I don't know if it makes sense to represent passwords in particular in the code as special kind of PromptableOption. For example an `@AllowOptionModifiers @PromtableOption(echo = false, promptName = "password", veifry=true) String newPassword` where the framework would include a prompt.

**Comment by remkop** [comment]
Interaction-wise, it should work, since the user will hit ENTER after their command, which kicks off the command line parsing. Then it seems okay from a user interaction point of view to display a password prompt on the next line and ask the user for more input... or am I missing something?

* `-option ${env:var}` would look up _var_ in the environment variables and initialize the field with the value (essentially same as your original post)
* `-option ${file:<path>}` would read the content from file `<path>` (essentially same as your original post)
* `-option ${password}` would display a password prompt and wait for user input. 
* `-option ${password:echo}`, similar, but would echo the password as the user types it. The prompt could be the `description` attribute of the `@Option` annotation.

It would be nice to make this extendable so application authors would be able to create their own lookups.

Thoughts?

**Comment by SagaciousZed** [comment]
`${}` would be pretty bad to use on any bourne compatible shell. I'm also a little hesitant in putting any kind of special characters and parsing into the value itself as that might lead to some unintended situations.

**Comment by remkop** [comment]
These are both good points and I'm starting to learn towards following the Keytool design with the modifier attached to the option name. 

One consideration is that in MSDOS, options look like `/X:value`, and similarly in PowerShell the `:` separator is commonly used to separate options from their values. Picocli should be able to support all these use cases. 

Also it would be nice to make this extendable somehow so that application authors can define their own modifiers and modifier handler.

**Comment by remkop** [comment]
Also something to think about: what should the generated documentation for option modifiers look like?

I can't find much precendence on the web. This one seems close: http://www.geomview.org/docs/html/Command-Line-Options.html

Different approach:
https://www.eiffel.org/doc/eiffelstudio/EiffelStudio%3A%20Using%20command%20line%20options

**Comment by SagaciousZed** [comment]
I don't have any experience with the MSDOS convention and the PowerShell convention. 

As for documentation generation, since this isn't a very common feature, I'm not sure the what makes sense as this isn't part of a clear convention. Documentation wise, sticking with established java tool convention might make sense given the the origin story. On the other hand, I don't think key tools documentation is especially clear.

**Comment by remkop** [comment]
I've thought about this some more and I was wondering if special support is really needed. One can already do this:

```
class Args {
    @Option(names = "-option", description = "the option value")
    String option;

    @Option(names = "-option:env", description = "the environment variable to look up for the actual value")
    String optionEnvKey;

    @Option(names = "-option:file", description = "path to the file containing the option value")
    File optionFile;
}
```

The usage help for such a class looks exactly as one would expect:
```
Usage: <main class> [-option=<option>] [-option:env=<optionEnvKey>] [-option:
                    file=<optionFile>]
      -option=<option>        the option value
      -option:env=<optionEnvKey>
                              the environment variable to look up for the
                                actual value
      -option:file=<optionFile>
                              path to the file containing the option value
```

Wouldn't it be better to leave the next step (calling `System.getenv(args.optionEnvKey)` or `Files.readAllBytes(optionFile.toPath())`) to the application?

**Comment by remkop** [comment]
To summarize, the password prompting feature is covered by this ticket: #82. Other than that, `-option`, `-option:env` and `-option:file` options are treated as separate options by picocli, which provides the building blocks to build a custom solution as described in my previous comment. 

I won't look further at providing special library support for option modifiers, unless something new comes up.

Still this is a good idea to either write an article about or mention in the user manual after #82 is implemented. (I added this to the list in the wiki: https://github.com/remkop/picocli/wiki/Plans-and-Notes-for-Future-Articles)
