### ISSUE TITLE
TypeConversionException message is ignored for options with arity can be 0

### ISSUE THREAD

**Issue by jsotuyod** [remkop/picocli#1760]
The documentation states that conversion errors can be reported back to the user by having the `ITypeConverter` instance throw a `TypeConversionException`. This however, seems to fail with options that have arity greater than 1.

Example code:
```java
public class PMDCLI {

    @Command
    public static class DummyCommand {
        @Option(names = "--single", converter = DummyConverter.class)
        private String single;

        @Option(names = "--multiple", converter = DummyConverter.class, arity = "0..*")
        private List<String> multiple;
    }

    public static class DummyConverter implements ITypeConverter<String> {

        @Override
        public String convert(String value) throws Exception {
            throw new TypeConversionException("invalid value: '" + value + "'");
        }
    }

    public static void main(String[] args) {
        new CommandLine(new DummyCommand()).execute("--single", "invalid");
        new CommandLine(new DummyCommand()).execute("--multiple", "invalid");
    }
}
```

Upon execution, the obtained output is:

```
Invalid value for option '--single': invalid value: 'invalid'
Usage: <main class> [--single=<single>] [--multiple[=<multiple>...]]...
      --multiple[=<multiple>...]

      --single=<single>
Unmatched argument at index 1: 'invalid'
Usage: <main class> [--single=<single>] [--multiple[=<multiple>...]]...
      --multiple[=<multiple>...]

      --single=<single>
```

Notice that for `--single` the message provided by the exception is used, but for `--multiple` this is completely replaced with "Unmatched argument at index 1: 'invalid'".

Is this maybe a message intended for positional parameters only?

**Comment by remkop** [comment]
This is by design:
When an option has `arity="0..*"`, the picocli parser cannot tell whether each next argument belongs to that option or to a positional parameter. It will try to assign to the option first, but it will take the type conversion exception to mean that we have reached the end of the parameters for that option, and this argument must be assigned to a positional parameter instead.

If it then cannot find a positional parameter, we end up with an unmatched argument, so that is what the user-facing error then shows.

Contrast this with a single-argument option: this has an implicit `arity="1"`, so the parser knows that the argument _must_ be assigned to that option. Hence, when a type conversion exception occurs, this can be reported to the end user directly.

**Comment by jsotuyod** [comment]
@remkop thanks for the prompt response. If my understanding is correct this can then happen under 2 circumstances:
- arity has a lower bound of 0
- arity has an upper bound of *

That is, even if I use arity `1..*`, past the first value (which I expect would be reported correctly), we fall back to the situation you described, right?

It does makes sense given your explanation, but maybe the docs could mention this. I was caught by surprise.

**Comment by remkop** [comment]
Good idea. I added text to the docs; it will show in the rendered HTML after the next release.
Thank you for raising this!
