### ISSUE TITLE
InitializationException: @Mixins are not supported on @ArgGroups

### ISSUE THREAD

**Issue by sebthom** [remkop/picocli#1793]
I am trying to use option sections as described here https://picocli.info/#_use_heading_to_enable_option_sections but for code re-use purposes I am working a lot with mixins. Trying to put a mixin into an arg group unfortunately results in `picocli.CommandLine$InitializationException: @Mixins are not supported on @ArgGroups`.

I would really appreciate if you could implement this.

**Comment by rsenden** [comment]
I'd like to see this functionality as well, as this would allow us to better reuse some standard option definitions and related functionality. Any particular reason why `@Mixin` is not supported in `@ArgGroups`?

Note that for using a single mixin class in an `@ArgGroup`, I guess the `ArgGroup` class could simply extend the mixin class to inherit all functionality provided by the mixin class. But obviously you can't use multiple mixins for an `ArgGroup` in this way, as Java doesn't support multiple inheritance.

Possibly you could refer to mixin classes using the `@ArgGroup` annotation instead of `@Mixin` from `ArgGroup` classes, but I guess this would have consequences for the help output.

**Comment by remkop** [comment]
> Any particular reason why `@Mixin` is not supported in `@ArgGroups`?

Think of it this way: a mixin is a partial `@Command`, and brings all or some attributes of a `CommandSpec`. That may include some options and positional parameters but is not limited to those. Mixins have many attributes that do not apply to arg groups.

My time available to work on picocli is extremely limited and frankly I don't see this happening in the near future.
