### ISSUE TITLE
need mixinStandardHelpOptions without `--version`

### ISSUE THREAD

**Issue by garretwilson** [remkop/picocli#1844]
I need a little clarification on something that is extremely minor. 🙂 A while back I realized that on one of my CLI applications, I was setting up subcommand help options incorrectly: I was using `subcommands = {HelpCommand.class}` when I really wanted to add `mixinStandardHelpOptions = true`. I didn't want a `help` sub-sub-command, but I want a `--help` option.

In other words if I want help for the for `foo bar` subcommand, I don't want to use `foo bar help` (maybe some people do, but I don't, for reasons explained in [GUISE-195](https://globalmentor.atlassian.net/browse/GUISE-195)); I want to use:

```
foo bar --help
```

But before making the commit, I double-checked the docs for [`@Command(mixinStandardHelpOptions = true)`](https://picocli.info/apidocs/picocli/CommandLine.Command.html#mixinStandardHelpOptions--). It would seem that in addition to `--help` option, this would also gives me a `--version` option!

```
foo bar --version
```

I already have `mixinStandardHelpOptions = true` set for the `foo` command; actually this set in the base CLI application class. But I have no need to know the version of a subcommand. Perhaps in some obscure use cases this would be useful, but for most use cases it doesn't even make sense. And it doesn't print out anything because as the docs notes I haven't set up any version information for the subcommand. (One might expect it to default to the parent command version info if none were specified; printing nothing doesn't seem helpful. Then again having the option doesn't seem helpful for the subcommand.)

So it would seem I want to add `mixinStandardHelpOptions = true` to the main command `foo` (as I already do), but only add `usageHelp = true` to each _subcommand_. Oop—there is no such option for the `@Command` annotation!

There needs to be a way to specify for subcommands that they need a `--help` option without giving them a useless `--version` option as well.

Again this is trivial, a tiny quibble. I just wanted to document it at least. Perhaps many people are using `mixinStandardHelpOptions = true` with subcommands without even realizing it gives a useless `--version` option, but it's not breaking anything and no one would likely have noticed it except for that one person who read the documentation. 😅

**Comment by remkop** [comment]
I have noticed this as well in my own applications, so I see where you are coming from and as a user I agree that I don't need a `--version` option on subcommands.

But like you also noticed, the pain is ... very bearable. 😅 
So, would introducing a new annotation attribute like `@Command(mixinHelp=true)` be an improvement, or would it just increase the cognitive load (yet another thing for users to look up) for a very minor gain? 

People can just have a `@Option(name = {"-h", "--help"}, usageHelp = true)` option. A bit more typing, but simple, no magic, less additional cognitive load...

I don't know. I doubt I will be putting much effort into changes in this area in the near future. 😔

By the way, I would recommend using a [version provider like the example](https://picocli.info/#_dynamic_version_info_with_variables) in the docs on all commands and subcommands, so the version comes from one place. The `${COMMAND-FULL-NAME}` will display the parent command name and the subcommand name so that may be useful.

**Comment by garretwilson** [comment]
Thanks for the quick reply.

I agree, this is completely live-with-able (although you might keep it open as a super-low-priority ticket when you want a break from bigger things). I just wanted to note it.

Please put your effort into #1707. There needs to be a low level way to hook into the conversion mechanism and provide our own conversions knowing the requested type. As it is right now, it's impossible.

**Comment by remkop** [comment]
Do you mean https://github.com/remkop/picocli/issues/1804 ?

**Comment by garretwilson** [comment]
Do you mean #1804 ?

Ah, yes. Sorry, I couldn't immediately find the ticket, and didn't see the link in #1707 (where the discussion started).
