### ISSUE TITLE
Document a pattern that do not return exit code

### ISSUE THREAD

**Issue by ttddyy** [remkop/picocli#1855]
I have been using picocli on the [micrometer-docs-generator](https://github.com/micrometer-metrics/micrometer-docs-generator) project and stumbled upon a problem that `System.exit` halt the maven process when exec-maven-java `exec:java` goal is used.

This is because `exec:java` uses the main maven process to invoke the target class and `System.exit` would simply halt the process that maven runs.

It is natural for a standalone CLI application to use the `System.exit`, but code invoked by some other application on the same process will have a problem using `System.exit`.

For my case, I initially tried to make the app a fat executable jar and make it invoked by `exec:exec` goal which spawns a new process, so it can use `System.exit`. https://github.com/micrometer-metrics/micrometer-docs-generator/pull/69
At the end, instead of the executable jar, I decided to go with simply throwing an exception AFTER `CommandLine#execute` is executed based on the returned exit code. 

```java
int exitCode = new CommandLine(new DocsGeneratorCommand()).execute(args);
if (exitCode != ExitCode.OK) {
    throw new IllegalStateException("DocsGeneratorCommand failed.");
}
```

I appreciate this pattern is also documented somewhere.
Since all I see is always using `System.exit`, it would be a problem for the environment where `System.exit` causes a negative effect such as `exec:java`.

**Comment by remkop** [comment]
Yes very good point! 👍 
Will you be able to provide a pull request for the [user manual](https://github.com/remkop/picocli/blob/main/docs/index.adoc)?
(Maybe a new section under [21. Tips & Tricks](https://picocli.info/#_tips_tricks), and we can link to that section from the [9.1. Exit Code](https://picocli.info/#_exit_code) subsection?)

Note that the [AutoComplete](https://github.com/remkop/picocli/blob/main/src/main/java/picocli/AutoComplete.java#L72) application had this exact same problem and uses System properties to decide whether to actually call `System.exit` or not. But that is just one idea. I just mention it because it may be useful to point to a concrete example from the doc.

**Comment by ttddyy** [comment]
Sure thing, I'll make a PR.

**Comment by remkop** [comment]
@ttddyy Thank you for your contribution!

I took the liberty to rewrite and add some examples. 
The updated documentation is now live in a new section called [Rare Use Cases](https://picocli.info/#_rare_use_cases).

Again many thanks!
