### ISSUE TITLE
Confusing usage message for collection options

### ISSUE THREAD

**Issue by AlexFalappa** [remkop/picocli#186]
The following test app:
```java
@CommandLine.Command(name = "app")
public class App {

    @CommandLine.Option(names = "-n", paramLabel = "NAME", description = "list of names", type = String.class/*, arity = "1..*"*/)
    List<String> names = new LinkedList<>();

    public static void main(String[] args) {
        App app = new App();
        CommandLine cl = new CommandLine(app);
        cl.usage(System.out);
    }

}
```
Produces:
```
Usage: app [-n[=NAME...]]
  -n= =NAME...]               list of names
```
It would be better something like this:
```
Usage: app [-n[=NAME...]]
  -n= [NAME [NAME...]]               list of names
```
Interestingly uncommenting the `arity` specification produces a better usage:
```
Usage: app [-n=NAME [NAME...]]
  -n= NAME [NAME...]          list of names
```

**Comment by remkop** [comment]
Oops. This is a bug. Thanks for letting me know!

**Comment by remkop** [comment]
Fixed in master, please confirm.
After this change, the usage message will be as below because of the changes made for #192:
```
Usage: app [-n=NAME]...
  -n= NAME                    list of names
``` 
The #192 change means that multi-value options (array, list, map fields) no longer greedily consume arguments. They just consume 1 arg by default. If the user wants to specify multiple values they need to specify the option multiple times:
```
app -n AAA -n BBB -n CCC
```
 
With arity uncommented (meaning that every `-n` option can be followed by one or more NAMEs), the usage looks like this:
```
Usage: app [-n=NAME...]...
  -n= NAME...                 list of names
```

**Comment by AlexFalappa** [comment]
I won't have a chance to try your latest improvements right now, sorry. I will try my best next week. 

However I like the change made for #192, an option consuming multiple arguments is confusing and should be avoided in favor of specifying that option more than once
