### ISSUE TITLE
Fix broken CI/CD pipeline

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#1930]
Fix broken tests:

* [x] a recent change used a Java 1.7+ API which results in broken tests when running on Java 1.6 or earlier:
```
:compileJava/home/runner/work/picocli/picocli/src/main/java/picocli/CommandLine.java:11634:
 <T>emptyEnumeration() is not public in java.util.Collections; 
cannot be accessed from outside package
```
The solution is to use `Collections.enumeration(Collections.emptyList())` instead.

* [x] Broken tests using `System.setSecurityManager` on Java 18-ea -> does not manifest on Java GA, separate ticket #1932

* [x] `ManPageGeneratorTest` has 3 failing tests (testEndOfOptionsWithoutOptions -  line 307, testNamelessCommand line 489 and testHiddenOptions line 242), likely related to https://github.com/remkop/picocli/pull/1896

* [x] Java 10 on Ubuntu fails the build due to a problem in `release-tasks.gradle`:
```
> startup failed:
  script '/home/runner/work/picocli/picocli/gradle/release-tasks.gradle': 1: 
  Can't have an abstract method in a non-abstract class. 
  The class '_BuildScript_' must be declared abstract or the method 
  'void init(java.lang.Object, org.gradle.internal.service.ServiceRegistry)' must be implemented.
   @ line 1, column 1.
     task bumpReadmeVersion {
```
This may be caused by [this change](https://github.com/remkop/picocli/commit/1f26852fba032c2e908afe8c019815211fd4c185#diff-40640fe1078ece83d7ea8fb67daacd77923a86d13447baf9769660b3b46f2ece) in gradle/wrapper/gradle-wrapper.properties, which bumped Gradle from 7.4 to 7.6...

Temporary fix is to revert to Gradle 7.4.

* [x] Flaky tests? Broken tests on Java 10 ubuntu:

```
picocli.HelpAnsiTest > testUsageMainCommand_ANSI FAILED
    org.junit.ComparisonFailure at HelpAnsiTest.java:442
stty: /dev/tty: No such device or address

picocli.HelpTest > testMapFieldHelp_with_unlimitedSplit FAILED
    org.junit.ComparisonFailure at HelpTest.java:2926

2327 tests completed, 2 failed, 27 skipped
```
Solution: skip non-LTS versions of Java

**Comment by wtfacoconut** [comment]
@remkop , In regards to the chanes made to `ManPageGenerator` from PR #1896, I'm currently looking at the three failed tests in `ManPageGeneratorTest` and I have a few questions/comments for you so that I can update the tests appropriately. 

## Test `testEndOfOptionsWithoutOptions`:
This test espects that if a command has no options, then the "options" section in the ascii doc will still get generated. Now that PR #1896 has been merged, do you still want an empty "options" section in the ascii docs to be generated, or would you like for the test to be updated to expect for that section to be missing?  

For reference, here's a screenshot showing a diff of the expected ascii doc vs the ascii doc that got generated: 
![image](https://user-images.githubusercontent.com/5297545/215015186-3ae84896-5738-49fe-971a-c88ad7716e43.png)

As a heads up, updating the test to simply expect a missing "options" section will be quick and easy as it will only require updating a resource file.

## Tests `testNamelessCommand` and `testHiddenOptions`:
These tests are failing simply because of an extra white space in various locations or newline that gets added. Not sure if this behavior is acceptable, but I think this is harmeless, so I'll just update the test cases to accept the extra new lines and white spaces. Based on the updates in #1896, it's not immediately obvious to me why this is now happening. Here's a screenshot of the diffs for reference.

Diff from `testNamelessCommand` failed test outputs. This one is when compairing `main_class.adoc`:
![image](https://user-images.githubusercontent.com/5297545/215017867-a43afd37-674d-4d19-8811-0f2ad81a30e7.png)

Diff from `testHiddenOptions` failed test output:
![image](https://user-images.githubusercontent.com/5297545/215016122-61e80590-b7a3-47e7-b186-94db7fd767ac.png)


To try and not hold you up, I've raised PR with updated test that just accept the whatever the newly generated stuff in the ascii docs. Please see PR #1940.

**Comment by remkop** [comment]
@wtfacoconut Thank you for the PR! Looks good and it is merged. Many thanks!
