### ISSUE TITLE
Repeatable commands async execution

### ISSUE THREAD

**Issue by sergproua** [remkop/picocli#1982]
I've created simple spring boot app which takes two commands A and B, each with required option -r and enabled repeatable commands so that I can run it with arguments 'A -r 1 B -r 2'

I'd like to see A and B commands executed asynchronously, is it possible?

Repo is here
https://github.com/sergproua/learn-picocli

**Comment by remkop** [comment]
Yes you can start a new thread in the `run` or `call` method of your command:

```java
@Command
public void MyCommand implements Runnable {
    @Option(names = "-x") int x;

    public void run() {
        new Thread() {
            public void run() { runInOtherThread(); }
        }.start();
    }
    private void runInOtherThread() {
        // business logic here
    }
}
````

**Comment by sergproua** [comment]
Yes, the solution will work. Is it possible to get list of commands in the top level command CommandRoot and execute all of them the way I want instead of default picocli command executor?

**Comment by sergproua** [comment]
Closing as it is discussed in #1194

**Comment by remkop** [comment]
Yes, the alternative you proposed in #1194 to use a custom execution strategy also works.

### Thread pool

Bear in mind that the mechanism you proposed ([parallel streams](https://docs.oracle.com/javase/tutorial/collections/streams/parallelism.html)) uses Java's fork-join framework's common pool. Unless specified otherwise, the number of threads in the common pool is equal to (the number of processor cores -1).
I imagine that on a machine with many cores, this will spin up many threads, potentially many more than the number of commands that will actually be executed. Not sure if this will significantly impact the performance of your application, but I just wanted to mention this so you are aware of it. If this could be a problem, one way to address this is with a custom thread pool:

```java
public class AsyncExecutionStrategy implements CommandLine.IExecutionStrategy {
    @Override
    public int execute(CommandLine.ParseResult parseResult) {
        List<CommandLine> cmds = parseResult.asCommandLineList();
        List<CommandLine> repeatable = filterRepeatable(cmds); // keep only the repeatable subcommands
        
        ForkJoinPool customThreadPool = new ForkJoinPool(repeatable.size());
        customThreadPool.submit(
            () -> repeatable.parallelStream().
                .forEach(commandLine -> new CommandLine.RunLast().execute(commandLine.getParseResult()));

        // BEWARE: this returns SUCCESS immediately
        // regardless of the result of the actually executed commands
        return 0; 
    }

    private List<CommandLine> filterRepeatable(List<CommandLine> all) {
        return all.subList(indexOfLastSubcommandWithSameParent(all), all.size());
    }
```

### Caution

Also, with this approach there are two more things your application becomes responsible for:
* figuring out which of the commands in the list returned by `ParseResult::asCommandLineList` need to be executed
* figuring out which exit code to return

#### Selection
I commented on #1194 with regards to the first issue, as it is a general problem with repeatable subcommands, not specific to async execution.

#### Exit code
Regarding the exit code, if your application cares about returning the correct exit code, you will need to collect the return values of `RunLast::execute` and select the most urgent value to return.

I will post the essence of picocli's internal implementation below, I don't think this is documented in the picocli user manual, but the approach is very similar to Spring's approach when multiple sources contribute exit codes:

```java
            List<Integer> candidates = resultsFromExecution();

            // Use the highest value (or if all values are negative, use the lowest value).
            int result = 0;
            for (int exitCode : candidates) {
                    if ((exitCode > 0 && exitCode > result) || (exitCode < result && result <= 0)) {
                        result = exitCode;
                    }
            }
```
