### ISSUE TITLE
extended/Longer Description options

### ISSUE THREAD

**Issue by alexanderankin** [remkop/picocli#2051]
Hi maintainers and users of picocli, i was wondering if there is a desire to have longer descriptions shown for --help vs -h on the CommandLine.Command annotation. I would propose that the --help (when mixinStandardHelpOptions is true) behavior change, and instead attempt to format and print the message in "fullDescription" before attempting to print the contents of "description" with the potential to pre-calculate this value in the annotation processing step. My main goal here is to start this discussion and assess whether this is something that is desirable to the maintainers and users (basically anyone besides myself). thank you.

**Comment by alexanderankin** [comment]
realizing that this same distinction between longer and shorter output can also be handled with a new boolean flag that enables the feature, and leaving description as is - the first line becomes a special case "summary" and the remaining part is only shown on the get_opt_long-style "--help" variant of the standard help option.

**Comment by remkop** [comment]
Currently the `-h` and `--help` give the same result. 
It would be surprising to end users to modify this behaviour.
Especially because in the usage help message, both `-h` and `--help` are shown on the same line with the same explanation, so they are clearly equivalent:

```
Usage: <main class> [-hV] 
  -h, --help              Show this help message and exit.
```


What you describe may be best accomplished with separate options for `-h` with some description and `--help` with some different description:

```
Usage: <main class> [-hV] 
  -h                      Show a short help message and exit.
      --help              Show a detailed help message and exit.
```
