### ISSUE TITLE
Interpolate '%', but not '${}'

### ISSUE THREAD

**Issue by VirtualTim** [remkop/picocli#2092]
I have some OptionSpec descriptions that contain properties I do not want interpolated, ie: `${test}`.
When I use `CommandSpec.interpolateVariables(false)` the `${test}` does not get substituted (what I want), however `%n` also does not get substituted. Ie:
```
      --openId.AuthorizationEndpoint=<authorization>
                            Endpoint for authorization.%nCurrent value: ${test}
```

The -help and -version options, generated via `CommandSpec.mixinStandardHelpOptions(true)` is now also incorrect.
What I expect:
```
  -h, --help                Show this help message and exit.
  -V, --version             Print version information and exit.
```
What I get with `interpolateVariables(false)`
```
      ${picocli.help.name.0:--h}, ${picocli.help.name.1:---help}
                            Show this help message and exit.
      ${picocli.version.name.0:--V}, ${picocli.version.name.1:---version}
                            Print version information and exit.
```

1. Is there a way to turn off interpolation for '${}', but leave it for things like `%n`?
2. Interaction between `mixinStandardHelpOptions` and `interpolateVariables` seems broken.

**Comment by remkop** [comment]
Hi @VirtualTim, thank you for raising this!

Would it help your use case to [escape](https://picocli.info/#_escaping_variables) the dollar sign with another dollar sign, like this: `$${test}` ?

An alternative to embedded `%n` newline format specifiers is to split the description for the option into multiple Strings. Just like multiple option names can be specified as an array of Strings, so can the description. Picocli will render each element of the description Strings array on separate lines. For example:

```java
@Option(names = "--openId.AuthorizationEndpoint", 
    description = { "Endpoint for authorization.",
                    "Current value: $${test}" })
```

**Comment by VirtualTim** [comment]
Thanks @remkop, that could kind of work, the issue is that I'm using picocli as a cli for a GUI application. So the current value is the actual value used in the GUI.
I realise that I could run string replacement on the description, and replace `$` with `$$`, but it seems inefficient. It seems weird/inefficient to programatically add a `$` only for picocli to later remove the `$` from the same string.

I guess that solution is probably good enough, I was just hoping that I missed a setting.

**Comment by remkop** [comment]
Hi @VirtualTim glad to hear that. 
Can I conclude that you have a solution for your use case and no further work is required for this ticket?

**Comment by VirtualTim** [comment]
Yeah that's fine, I was just hoping for a more idiomatic solution.

Do you consider the interaction between `CommandSpec.mixinStandardHelpOptions(true)` and `CommandSpec.interpolateVariables(false)` a bug?
Would you like me to raise a separate issue?

**Comment by remkop** [comment]
The `CommandSpec.mixinStandardHelpOptions(true)` mixin is defined with variables, by design, to allow applications to customize the help options names without needing to define these options from scratch in their application. 

There's a common use case that people want a lowercase short option `-v` for version information, as opposed to the standard built-in uppercase `-V` option. This use case is easily served with the variables. 

However the variables get in the way for your use case where you want to reuse description strings between a GUI application and a CLI application. I believe this is a rare use case that requires a solution in the application, not in the picocli library. 

Some solutions that come to mind are defining your own help/version options without variables, or replacing `$` dollar characters in the descriptions with double `$$` dollars before using those descriptions in the CLI.
