### ISSUE TITLE
Allow user to overwrite Collection field default value

### ISSUE THREAD

**Issue by wiwie** [remkop/picocli#216]
Right now, if an option field is a Collection and is initialized with a default value in the code, and at the same time the user code is invoked with parameters for that collection field, these parameters are appended to the existing collection.

However, in my eyes it would make more sense to reinitialize the field with a new collection only containing the user-passed parameters. This is at least, what I expected.

Right now, there is no way of me saying "use only the parameters I passed in, and forget about the default one".

**Comment by remkop** [comment]
Yes, that makes sense. It will require some work to keep track of the original default values so we only replace the original collection with a new collection when the first user-specified option is matched, and for subsequent options _add to_ (and don't replace) the new collection.

**Comment by wiwie** [comment]
true, that was an oversight I had in the temporary "fix" I incorporated in my fork. Any idea, how to achieve this? Maybe introduce a boolean flag for each option, whether the current field value is user-specified?

**Comment by remkop** [comment]
If you want to create a pull request, perhaps add a `Set<Field>` field in `Interpreter` with fields that have been modified during parsing? Clear the set at the start of parsing, and check if it already contains the field before creating a new collection or array? Any time a field is modified while parsing the command line, add the field to the set.

Otherwise (without modifying the code), the workaround is similar to #213: keep the default value `null`, document the default value in the option description and initialize the default in the application if the user did not specify any values.

Note that this use case (a collection or array with multiple default values) is not covered nicely by JCommander's `IDefaultProvider`, so still thinking about what would be a nice way to do #213...

**Comment by remkop** [comment]
Implemented: parsed values are no longer appended to, but instead replace, the default value of multi-value (array, Collection or Map) options and positional parameters.
