### ISSUE TITLE
run not return  cli

### ISSUE THREAD

**Issue by Zihan0409** [remkop/picocli#227]
when i run testng test，the test is over,but the cli not quit.
code:
public static void main(String[] args) {
        LoggerUtil.initLogger();
//        args= new String[]{"-t","CreateAndDeleteActiveTest.properties"};
        CommandLine.run(new DiffMain(), System.err, args);
        System.out.println("return  main ");
        return;
    }

    @Override
    public void run() {
        if (this.testFileName != null) {
            setConfig();
            Class[] cls = new Class[1];
            if (this.isThrift) {
                cls[0] = ThriftTestFactory.class;
            } else {
                cls[0] = HTTPTestFactory.class;
            }
            //初始化测试用例，并设置报告的格式
            TestNG testNG = new TestNG();
            testNG.setTestClasses(cls);
            testNG.setUseDefaultListeners(false);
            List<Class<? extends ITestNGListener>> list = new ArrayList();
            list.add(JsonReportNG.class);
            list.add(JUnitXMLReporter.class);
            testNG.setListenerClasses(list);
            logger.info("start test");
            testNG.run();
            logger.info("end test");
            return;
        }
        CommandLine.usage(this, System.err);
        return;
    }

the run log:
Command line suite
Total tests run: 2, Failures: 0, Skips: 0
===============================================

17-11-01 18:08:16,293 [main] INFO  c.m.h.s.d.c.DiffMain(DiffMain.java:89) ## end test
return  main

**Comment by remkop** [comment]
The process output looks correct:
* The call to `CommandLine.run(new DiffMain(), System.err, args)` returns correctly, because we can see the `return main` in the output.
* The `DiffMain::run` method executed correctly because we see the `end test` logging output.

Do you mean the process does not exit? Is there anything in DiffMain or in TestNG that starts a non-daemon thread? 

You can check which threads are still running by executing `jstack <PID>`. You can get the PID (process id) of your java process by executing `jps` - this will list all Java processes with their process IDs (both `jps` and `jstack` are in $JDK_HOME/bin).

See also:
https://docs.oracle.com/javase/8/docs/technotes/tools/unix/jps.html
https://docs.oracle.com/javase/8/docs/technotes/tools/unix/jstack.html

**Comment by remkop** [comment]
Does this answer your question?

**Comment by remkop** [comment]
If the problem not resolved, can you give more information?
I am not sure what you mean by "the cli not quit".

**Comment by remkop** [comment]
I hope my answer was useful. I will close this ticket for now.
Please reopen if the problem persists or open a separate ticket if you have additional questions.
