### ISSUE TITLE
[Feature Request] Option dependencies

### ISSUE THREAD

**Issue by jusw85** [remkop/picocli#295]
Would be nice to specify option dependencies i.e. if an option is present, another option must also be present.

Reference example ('requires' flag):
https://github.com/kbknapp/clap-rs/blob/master/examples/07_option_args.rs
https://docs.rs/clap/2.31.1/clap/struct.Arg.html#method.requires

Usage example:
```
# ./pointorline --start=5,5 # start can exist by itself
# ./pointorline --end=10,10 # end cannot exist without start, error!
```

Right now it's possible to check this after parsing is done, so it's not a pressing issue, but it would be nice to have.

**Comment by remkop** [comment]
Ok, interesting. 
There are other tickets I want to work on first but if anyone submits a pull request with unit tests I have no objection to supporting this functionality.

**Comment by lenkite** [comment]
It would be great to also have some way of specifying option alternatives. Like in the below `-u`, `-p`, `-c` are only required if `-P` is not present.

```
list-nodes -c <controlHost> -u <user> -p <pass>  OR list-nodes -P <profileName>
```

**Comment by remkop** [comment]
Related: #199 will give support for mutually exclusive options. Currently I don’t think that ticket mentioned making a single option exclusive with a group of options. It may be good to make a note of this idea on the #199 ticket. 

What may be interesting for your use case is that picocli already allows you to specify a _custom synopsis_ to show which options are mutually exclusive: http://picocli.info/#_custom_synopsis

**Comment by lenkite** [comment]
Thanks for the advice. I have added a note to the #199 ticket. For now, I will add a custom synopsis as you suggest.

**Comment by remkop** [comment]
> _This is a [cross-post](https://github.com/remkop/picocli/issues/199#issuecomment-462600651) from #199. Future updates will be on the #199 ticket, so please check there for updates._

A first cut of support for `ArgGroup`s has landed in master. This adds support for:

* mutually exclusive options and positional parameters (`exclusive = true`)
* co-occurring options and positional parameters (`exclusive = false`: require all elements in the group, or none)
* composite groups
* groups can be required or optional

Example:

```java
 @Command(argGroups = {
         @ArgGroup(name = "EXCL",      exclusive = true,  required = true),
         @ArgGroup(name = "ALL",       exclusive = false, required = true),
         @ArgGroup(name = "COMPOSITE", exclusive = false, required = false,
                   subgroups = {"ALL", "EXCL"}),
 })
 class App {
     @Option(names = "-x", groups = "EXCL") boolean x;
     @Option(names = "-y", groups = "EXCL") boolean y;
     @Option(names = "-a", groups = "ALL") boolean a;
     @Option(names = "-b", groups = "ALL") boolean b;
 }
```

This defines a composite group with the following synopsis:
```
[(-x | -y) (-a -b)]
```

The composite group consists of the required exclusive group `(-x | -y)` and the required co-occurring group `(-a -b)`.

Valid user input for this group would be:
* no options at all (because the composite group itself is non-required)
* -x -a -b (in any order)
* -y -a -b (in any order)

Any other combination of `-x`, `-y`, `-a` and `-b` would give a validation error.

----
Still TODO:
* show group synopsis in usage help message
* show group headings in options list
* update annotation processor in `picocli-codegen` to build a model from the new annotations at compile time
* documentation in user manual and release notes

That said, the majority of the functionality is there.
I would appreciate it if people would try this to see if it meets their requirements and to find any places where the API should be improved.

**Comment by remkop** [comment]
Picocli 4.0.0-alpha-1 has been released which includes support for options that must co-occur (dependent options).
See https://picocli.info/#_argument_groups for details.

_Please try this and provide feedback. We can still make changes._

_What do you think of the annotations API? What about the programmatic API? Does it work as expected? Are the input validation error messages correct and clear? Is the documentation clear and complete? Anything you want to change or improve? Any other feedback?_
