### ISSUE TITLE
simplify kotlin example in documentation

### ISSUE THREAD

**Issue by virtuald** [remkop/picocli#372]
Instead of

```
@Command
class MyApp {
    ...
    companion object {
        @JvmStatic fun main(args: Array<String>) {
            CommandLine.run(MyApp(), System.err, *args)
        }
    }
}

```

It's easier to do this instead:

```
@Command
class MyApp {
    ... 
}

fun main(args: Array<String>) = CommandLine.run(MyApp(), System.err, *args)
```

Idea borrowed from [clikt](https://ajalt.github.io/clikt/whyclikt.html)'s documentation.

**Comment by virtuald** [comment]
Sure... where do the docs live?

**Comment by remkop** [comment]
docs/index.adoc

**Comment by virtuald** [comment]
Oops, I meant to do it today but got busy... thanks!

**Comment by remkop** [comment]
No problem at all! Thanks for the suggestion!

**Comment by lpar** [comment]
Hmm, maybe this worked at the time, but it doesn't work now:

`fun main(args: Array<String>) = CommandLine(MyApp()).execute(*args)`

Because `execute` returns an int, Kotlin deduces that main returns an int, so you get a warning saying that `main` should return `Unit`. If you ignore that you get a run-time error:

>Error: Main method must return a value of type void in class mypkg.MyAppKt, please 
define the main method as:
>   public static void main(String[] args)

So I think it should be

```
fun main(args: Array<String>) {
  CommandLine(MyApp()).execute(*args)
}
```

**Comment by remkop** [comment]
@Ipar, thanks for catching that!
My bad, I didn’t verify the Kotlin example with the new `execute` API. 
I’ll fix this as soon as possible.

**Comment by remkop** [comment]
@lpar Thanks again for the bug report!
I fixed the user manual.
