### ISSUE TITLE
Incorrect error message for parameter arity

### ISSUE THREAD

**Issue by sisidra** [remkop/picocli#409]
Example:
```java
  @Parameters(arity = "1..*", paramLabel = "FILE")
  private List<File> files;
```
Expected output:
```
Missing required parameters at positions 1..*: FILE
```
Actual output:
```
Missing required parameters at positions 0..*: FILE
```

Or am I missing something?

**Comment by remkop** [comment]
The index for positional parameters is zero-based. For example, an app that takes two positional parameters could look like this:

```
class Point {
    @Parameters(index = “0”) int x;
    @ Parameters(index = “1”) int y;

    // ...
}
```

In your case the positional parameter is a `List`, so its `index` becomes `“0..*”` by default. 

The `arity` attribute specifies _how many_ parameters an option or positional parameter consumes. Your application specifies `“1..*”` which means “at least one”. 

The `index` attribute tells the parser _from which position_ to start consuming parameters.

**Comment by lndbrg** [comment]
Sure, it's slightly confusing for developers using the library and also for users. A better error message and/or better docs would be fantastic :)

**Comment by remkop** [comment]
I'm open to concrete suggestions. A pull request would be even better! :-)

**Comment by remkop** [comment]
How about if I changed the error message to

```
Missing required positional parameter(s) at index 0..*: FILE
```

Would that clarify things?

**Comment by lndbrg** [comment]
I think that is a leaky abstraction for the users of the CLI. If an application requires at least one file, saying that instead of exposing the range error would be better as I believe the leakage of the range is just confusing.

I'm going to think a bit more about this and see if I can come up with something 🙂

**Comment by remkop** [comment]
Still thinking about that error message. Perhaps this is better:
```
Missing required FILE parameter at position index 0..*
```

**Comment by lndbrg** [comment]
Hmm, so I think one of the disconnects is the impedance mismatch between the generated help and the dumped range. The fact that it's stored in a 0 indexed data structure is an implementation detail. 

The example help shows the name of the var and that it's required (according to standard unix man page/help format)
```
Usage: <main class> [-f=FILE] [-n=<number>] NUM <host>
      NUM        number param
      host       the host parameter
  -f= FILE       a file
  -n= <number>   a number option
```

The error message I would suspect from the first if i fail to provide the parameter for `NUM` would be something like (I probably would prefer the term argument over parameter, but that's a nit pick):
`Missing 1st required parameter NUM`

Or in another example from the documentation:
```
Usage: <main class> <host> <port> [<files>...]
      host    destination host
      port    destination port
      files   files to transfer
```

If i forgot host in the second example:
`Missing 1st required parameter host`

For port i would expect:
`Missing 2nd required parameter port`

And for files i would expect:
`Missing 1 or more values for 3rd required parameter files`

I strongly believe that translating them to where they are expected in the command line, rather than where they are expected in the index is preferable and more helpful to users.

In your example:
```
class App {
    @Parameters(index = “0”) int x;
    @Parameters(index = “1”) int y;
    @Parameters(index = “2..3”) String[] abc;
    @Parameters(index = “4..*”) int[] xyz;
    @Parameters(index = “0..*”) String[] all;

    // ...
}
```
Running that as a cli named `foo` (missing the second string for `abc`):
`foo 5 6 mystring`
The error message I would expect as a user I think would be:
`Missing 2nd value for 3rd required parameter abc`

I might even forgo the number of the required parameters, turning the message to:
`Missing required parameter NUM`
`Missing required parameter host`
`Missing required parameter host`
`Missing 1 or more values for required parameter files`
`Missing 2nd value for required parameter abc`

**Comment by remkop** [comment]
I fixed this to omit the reference to the index range. After the change, the error message looks like this:

```
Missing required parameter: FILE
```

**Comment by remkop** [comment]
This is fixed in the latest release https://github.com/remkop/picocli/releases/tag/v3.3.0
