### ISSUE TITLE
Discrepancy between ArgSpec::completionCandidates() and ${COMPLETION-CANDIDATES}

### ISSUE THREAD

**Issue by rpanak** [remkop/picocli#412]
There's a discrepancy between `ArgSpec::completionCandidates()` and `${COMPLETION-CANDIDATES}`. In case of `enum`, `${COMPLETION-CANDIDATES}` gets resolved to `enum` constants even though no candidates have been explicitly set. I think this is correct behavior, but in the same situation `ArgSpec::completionCandidates()` returns `null`. The JavaDoc for `description()` is clearly not describing the current state of things as it says:

> The string ${COMPLETION-CANDIDATES} is replaced with the completion candidates generated by completionCandidates() in the description for this option.

**Comment by remkop** [comment]
Thanks for the PR.
You are correct that any specified `completionCandidates` were being ignored for enums.

I did not anticipate that users would want to use different completion candidates than the enum values.
Note that if the completion candidates suggest non-enum values, the parser will reject such values since they cannot be assigned to the enum! (Unless a custom type converter is specified.)

So it seems a bit dangerous. Can you explain the motivation behind allowing non-enum value completion candidates?

**Comment by remkop** [comment]
Actually, the special type converter is a good use case. 

```java 
enum Digit implements ITypeConverter {
  one(“1”), two(“2”), three(“3”);

  private final String userValue;

  Digit(String v) { this.userValue = v; }

  public Digit convert(String value) {
    // convert “1” to `one`, “2” to `two` etc
  }
}
```
Example app:
```
class App {
  @Option(names = “--digit”)
  Digit myDigit;
}
```

This allows command lines like 
```
<cmd> --digit 1
```

**Comment by rpanak** [comment]
To be honest I didn't give it much thought as it hadn't been my use case. I just wanted to react to an Exception (wrong argument value) by telling the user a comprehensible message with possible values listed. `ex.argSpec.completionCandidates` seemed like a good bet but much to my surprise, it offered nothing, unlike `${COMPLETION-CANDIDATES}`.

However, if nothing else, you can follow Java naming convention with `ENUM_VALUES` (maybe because you want to reuse the enum somewhere in the code). At the same time it allows you to keep the command line values more user friendly. Basically almost something like your example.
