### ISSUE TITLE
Support shared options between parent command / subcommands

### ISSUE THREAD

**Issue by li-wjohnson** [remkop/picocli#580]
I couldn't find this in any other issues or the documentation. Excuse me if I'm missing something.

I'd like to support a shared option across all commands and subcommands. For example, if you provide '--stacktrace' anywhere in the args, any errors printed will include the stacktrace. 

I know I could use a Mixin or inheritance to define the --stacktrace option for all (sub)commands, but (afaik) that would define separate boolean options for each, and which option is true depends on where in the args the user put '--stacktrace'. Then, figuring out if --stacktrace was provided means iterating over all parent commands and seeing if any are true.

It would be nice if I could configure unmatched options to instead match on parent command options. Then, only the root command would need to define '--stacktrace'. 

Now that I think about it, I could use `@Option` on a setter method, and set a static boolean value. Maybe this is something that could go in the documentation?

**Comment by remkop** [comment]
Hi @li-wjohnson, thanks for using picocli!

I think your idea should work: the combination of a Mixin that defines an `@Option` on a setter method, where the method implementation sets a static boolean.

Can I ask you a favor? I've noticed that other projects, like JUnit 5, use StackOverflow for building up a knowledge base of generated and maintained by the community. I think that is a great idea, because Google indexes StackOverflow so these questions and answers come up in Google searches.

I think your question would be a great candidate for an entry in StackOverflow. It may also help spread awareness that picocli exists when it is mentioned in many command line parsing questions on StackOverflow. What do you think? 

In addition, if you see a nice way to weave this into the picocli user manual, it would be great if you could provide a patch or pull request.

**Comment by remkop** [comment]
@li-wjohnson I created this StackOverflow question to help create a knowledge base: https://stackoverflow.com/questions/54207862/picocli-how-to-share-options-between-parent-command-and-subcommands/54207863#54207863

If you can see a nice way to weave this into the picocli user manual, it would be great if you could provide a patch or pull request.
