### ISSUE TITLE
addSubcommand without name or alias

### ISSUE THREAD

**Issue by andrewbleonard** [remkop/picocli#611]
CommandLine.addSubcommand requires a string name and optionally an array of aliases.  Would it be possible to add a version of addSubcommand that just takes in an Object and reads the name and aliases from the @Command annotations?  If the subcommands annotation can get the name and alias for subcommands, it seems like the programmatic way of adding subcommand should be able to as well.

**Comment by andrewbleonard** [comment]
That makes sense to me.

**Comment by remkop** [comment]
I'd love to include this in picocli-4.0, but there are a lot of items on the [todo list for that release](https://github.com/remkop/picocli/milestone/40)...

Do you think you will be able to provide a pull request with unit tests?

**Comment by remkop** [comment]
This is now available in master. It tries to get the name from the `@Command(name = "...")` annotation, otherwise from the first `@Command(aliases = {"..", "..."})` alias. Should also work for programmatically constructed `CommandSpec` and `CommandLine` objects, without an annotated user object.

If no name is found, an `InitializationException` is thrown.

Can you verify this works as expected?
