### ISSUE TITLE
Provide more context information to IVersionProvider.

### ISSUE THREAD

**Issue by garretwilson** [remkop/picocli#629]
Thanks for a truly awesome and well-thought-out library!

I'd like to request some additions to the `IVersionProvider` approach. The problem is that it requires some static strategy that will be instantiated when the annotations are processed, and this make it very hard to provide any dynamic information for subclasses. That is, if I wanted to create a convenience base CLI application class that would automatically look up a version, currently each actual CLI application has to implement a lot of boilerplate. Let me explain.

Our applications use Maven, and it's straightforward to have the a properties file such as `MyApp-config.properties` which Maven automatically updates with the version number when it builds the project. Currently for one application I'm using a version provider that simply looks up the config properties from the program resources. This works fine for a single application, but it's hard-coded to know the actual application class (in order to use its class loader and find the properties file in resources).

What we need is more contextual information in the `IVersionProvider` interface which would tell the strategy the name of the class for which a version is being retrieved. Something like this:

```java
public interface IVersionProvider {
  String[] getVersion(Class<?> commandClass) throws Exception;
}
```

Since you're processing the class annotated by the `@Command` annotation anyway, picocli knows what class it's getting metadata for, so it can pass that class to `getVersion()`. This would be immensely helpful. Then we would simply need to use something like this:

```java
@Command(name = "foobar", description = "…",
    versionProvider = ResourcesVersionProvider.class, mixinStandardHelpOptions = true)
public class Foobar {
  …
}
```

Now the `ResourcesVersionProvider` would receive `FooBar.class` the `getVersion()` call, and it would know where to find the version information (which Maven would have updated). Each CLI application could reuse the `ResourcesVersionProvider` strategy class and wouldn't have to make a new one each time.

If you like the idea but don't have the time, I could look into contributing the changes if you're open to help. (P.S. We could really use a `INameProvider` as well, for the same reasons. We put that in the POM, so why not let Maven update that for us as well.)

**Comment by garretwilson** [comment]
One reason we don't want to use the pre-built `ManifestVersionProvider` is that, if I understand it correctly, it pulls things out of the JAR manifest, which assumes we have build a JAR. The Maven-updated properties file approach outlined above is easier to use in development, and theoretically gives us access to any Maven properties. It works well running within IDEs as well, before we even build a JAR.

**Comment by remkop** [comment]
Glad to hear you like picocli!

I like your idea, I can see the benefit that you could have a single version provider implementation that can be reused for multiple different commands.

Two small tweaks: 
1. Instead of providing the user object, I propose we provide the `CommandSpec` of the command whose version is requested. Implementors can call `commandSpec.userObject()` to get the instance of the class that was annotated with `@Command`. The advantage is that this would also work for applications that use the programmatic API instead of the annotations.

```
String[] getVersion(CommandSpec command) throws Exception;
```

2.  I want to avoid breaking backwards compatibility. This means we cannot add a method to the `IVersionProvider` interface or change the signature of its `getVersion` method.  We will likely have to introduce a new interface (`IVersionProvider2` ?) with the new method. To integrate this, we can either:

* introduce a new attribute `@Command(versionProvider2 = Class<? extends IVersionProvider2>, ...)` in addition to the `@Command(versionProvider=...)` attribute
* let `IVersionProvider2` extend `IVersionProvider` 

The drawback of the first solution is that picocli would need additional methods to get and set the versionProvider2 in addition to the versionProvider (where likely users will only specify one, if they specify both we pick v2). This API may also be confusing to users.

The drawback of the second solution is that users implementing `IVersionProvider2` would need to implement two methods: the original no-arg `getVersion` method, as well as the new `getVersion(CommandSpec)` method. (The implementation of the no-args method can be empty.)

Thoughts?

Putting it together:
```
public interface IVersionProvider2 /*extends IVersionProvider ?*/ {
  String[] getVersion(CommandSpec command) throws Exception;
}
```

Once we flesh out the solution to the backwards compatibility issue, it would be great if you could provide a pull request or a patch. We will also need to update the user manual.

**Comment by remkop** [comment]
`IVersionProvider2 extends IVersionProvider` is probably the way to go. Thoughts?

**Comment by garretwilson** [comment]
Oh, first a little complaint: the approach to naming the interfaces starting with `I` is not idiomatic to Java. Today's thinking is to program to interfaces anyway, and the interface represents the "thing", so convention would be just to call it `VersionProvider`. I don't expect you to go changing them all, I just thought I'd mention it, because suddenly having a `IVersionProvider2` brings back nightmares of the Microsoft COM days. 😱 hehe

Anyway this is easily solved: in the `IVersionProvider` interface, create `getVersion(CommandSpec command)` with a default implementation that delegates to the legacy `getVersion()` method:

```java
public interface IVersionProvider {
  …
  default String[] getVersion(CommandSpec command) throws Exception {
    return getVersion();
  }
}
```

picocli will now call `getVersion(commandSpec)`. The old code will continue to work just fine. And new code will implement `getVersion(CommandSpec)` instead of `getVersion()`. Actually people can choose which one to implement (although they can't implement both unless they make sure they call the other one themselves, or delegate to the default implementation).

But I just saw on your page that you don't require Java 8, so default methods would be a problem. But do you really intend to continue support of earlier Java versions!? Why? I think that's going to be a lot of wasted effort (and missed opportunities for better code) for little benefit. Who has a Java 5 application they are retrofitting to use picocli without upgrading to at least Java 8??

Yes, I love the idea of sending a `CommandSpec`. The more context the better.

As I mentioned the same sort of thing applies to a lot more than just version. In the future we should discuss what sort of general metadata interface we could provide. I would love to tie in my [Rincl](https://rincl.io/) library (I haven't added annotations to it yet) so that we could have localized descriptions, etc.

But small steps first. What do you think about the default method approach? I really don't like the versioned interface approach.

Oh, and for pull requests, do you prefer we make them from a branch in the existing repository, or do you want us to fork the repository and make a pull request from the fork?

**Comment by remkop** [comment]
> Yes, I love the idea of sending a `CommandSpec`. The more context the better.

Cool.

The question of why Java 5 came up before a few times, so I created a wiki entry in the [FAQ](https://github.com/remkop/picocli/wiki/FAQ#why-support-java-5) to avoid repeating the same discussion. Let me know if there's a consideration that I missed.

About the `IInterface` naming convention, that ship has sailed...

About pull requests, I thought GitHub requires you fork the project before you can make a PR, I could be wrong.

**Comment by garretwilson** [comment]
I don't want to get into a big argument about the Java 5 thing; it's your library so ultimately it's your decision. But just a couple of reactions:

> There are many (mostly corporate) environments with systems that are stuck on older versions of Java.

Really!? Do you have any statistics on how many actual users are stock on Java 5 in 2019? Even last year few Java projects are using less than Java 8 (https://www.baeldung.com/java-in-2018). And are any of those old versions actually using picocli?

> There may not be many users in this situation, but I see no reason to exclude them.

Here are a couple of reasons:

* At a certain point, you'll have to determine whether keeping a couple of users will hold back the entire library moving forward. And do you actually have any numbers of how many people _really_ are still on Java 5? I'm highly skeptical that there are many, even in huge corporate environments. Those versions aren't even supported by Oracle anymore, so they are likely a security risk anyway.
* You also have to realize that in a way _you_ are holding _them_ back. The more libraries that refuse to support ancient Java versions, the more incentive their IT departments have to update. It's the same reasoning of why we should _not_ support IE6 anymore; people should move on, and the browser should die. Continuing to support ancient versions is only furthering the problem.

> Java 5 has all the facilities that are needed.

…except now we see that Java 5 does _not_ have all the facilities that are needed. Instead we're having to create unwieldy workarounds that will live with the library forever, in order to support a need that might not even exist (and certainly won't exist for much longer).

Anyway I'm opinionated but I don't want to detract from how great picocli is.

**Comment by garretwilson** [comment]
> About pull requests, I thought GitHub requires you fork the project before you can make a PR, I could be wrong.

If you [add someone as a collaborator](https://stackoverflow.com/a/7920363/421049) they can make pull requests directly.

You don't know me or my code yet, so I'm not asking to be added as a collaborator unless you want to. I was just passing along the info. I'll be happy to fork and create a pull request from that.

**Comment by remkop** [comment]
If you could create a fork/PR that would be great. Please also add some unit tests, ideally keeping the code coverage at least at its current level. Maybe also add some text to the [user manual](https://picocli.info/#_dynamic_version_information) if you're up for it.

**Comment by remkop** [comment]
Note that an alternative solution would be to delegate to a shared version provider, something like this:

```java
@Command(name = "foobar", description = "…",
    versionProvider = Foobar.VersionProvider.class, ...)
public class Foobar {
    @Spec static CommandSpec spec;
    …

    static class VersionProvider implements IVersionProvider {
        public String[] getVersion() { return ActualVersionProvider.getVersion(spec); }
    }
}
```

This can be done with the current version of picocli.

**Comment by garretwilson** [comment]
I wanted to circle back and give an update on this.

The way I've been getting around the problem is adding this static internal class in my base class `BaseCliApplication`:

```java
protected static abstract class AbstractMetadataProvider implements IVersionProvider {

  private final Class<? extends Application> applicationClass;

  @Override
  public String[] getVersion() throws Exception {
    //here I load the version from resources based upon the applicationClass variable
  }

  public AbstractMetadataProvider(@Nonnull final Class<? extends Application> applicationClass) {
    this.applicationClass = requireNonNull(applicationClass);
  }

}
```

Then in each application subclass will have its own subclass of the internal class, like this:

```java
static class MetadataProvider extends AbstractMetadataProvider {
  public MetadataProvider() {
    super(MyApp.class);
  }
}
```

Note that we slip in `MyApp.class`, which is the magic that tells the version provider what class is using it. Then in the actual `MyApp` class itself, I add `versionProvider = MyApp.MetadataProvider.class`.

That way I get a little reuse, and I try to lower the risk of error. But it's still a roundabout solution, and it shouldn't be necessary.

As I mentioned earlier in this ticket, I would be happy to update the source code to pass the command to `IVersionProvider`. But I'm hesitant to create some hacky solution where we start versioning the interfaces or otherwise (`IVersionProvider2`) is so ugly, confusing, error-prone, etc. And even worse, the library will be stuck with this forever. Even when (likely in the near future) you switch to a more recent version of Java, which obviates the need for the hack, the library will be stuck with with this cruft.

So the reason I haven't pitched in and contributed this already is that I'm still mulling whether it's worth the effort, especially in light of #649. Like I said, I want to help. But I also don't want to make a mess and prefer to do it right.

**Comment by remkop** [comment]
Yes, I agree that the IVersionProvider2 solution is not beautiful...  :-)

It sounds like, given the choice between adding a `IVersionProvider2` extension and your workaround above, you prefer to keep the library as is and use the workaround you described, is my understanding correct?

**Comment by remkop** [comment]
Instead of an interface, it may be better to add an `AbstractVersionProvider` class to picocli. This class will have a no-op implementation of the parameterless `getVersion` method prescribed by `IVersionProvider`, and an abstract method that takes a `CommandSpec` parameter:

```
abstract class AbstractVersionProvider implements IVersionProvider {

  public /*final?*/ String[] getVersion() {
    throw new UnsupportedOperationException();
  }

  /**
   * Subclasses should implement this method to return 
   * version information for the specified command.
   *
   * The intention is that a custom subclass
   * can be reused across multiple commands. 
   */
  public abstract String[] getVersion(CommandSpec command) throws Exception;
}
```

This is less ugly than `IVersionProvider2`, and is less confusing since it’s clear what implementors need to do. The only drawback is that subclasses are less flexible than interfaces but in this case the pros outweigh the cons I think. 

Thoughts?

**Comment by garretwilson** [comment]
> It sounds like, given the choice between adding a IVersionProvider2 extension and your workaround above, you prefer to keep the library as is and use the workaround you described, is my understanding correct?

Using my workaround would be a temporary solution until I simply write my own framework. I'd rather write it and do it write than add messy code to your framework and then wind up writing my own anyway.

I'm not sure I understand your `AbstractVersionProvider` proposal. Are you saying that the Picocli framework would detect at runtime if an implementation was using the `AbstractVersionProvider`, and if so, the behavior would switch and be totally different than what the `IVersionProvider` indicates? If so, that is (since you asked for my thoughts) easily the worst of all the options we've discussed here, in my opinion.

This completely breaks the contract of `IVersionProvider`, which is a complete no-no. (See the [Liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle).) Basically what it is saying that "we have an interface named `Good`, but our implementation has some secret behavior so that if the implementation is the `BadImpl` class, what is purported to be good is treated as bad!!

Implementing `IVersionProvider` is a contract for certain semantics and behavior. If the implementation does not adhere to the contract (not even in the least! it does something completely different), why does `AbstractVersionProvider` advertise itself as adhering to something it doesn't?

**Comment by remkop** [comment]
> the Picocli framework would detect at runtime if an implementation was using the AbstractVersionProvider, and if so, the behavior would switch (...)?

Yes, but this is common for all solutions we discussed so far. Even with Java 8 default methods on interfaces, picocli would need to decide at runtime whether to invoke the parameterless `getVersion` method or not.

**Comment by remkop** [comment]
Didn’t mean to close. Pressed wrong button on phone screen.

**Comment by garretwilson** [comment]
> Yes, but this is common for all solutions we discussed so far. Even with Java 8 default methods on interfaces, picocli would need to decide at runtime whether to invoke the parameterless `getVersion` method or not.

No, maybe you didn't understand my proposal. Let me explain. (I understand that you don't want to use `default`, and I'm not arguing, I'm just trying to explain the misunderstanding.) Here is `IVersionProvider` now:

```java
public interface IVersionProvider {
  /**
   * Returns version information for a command.
   * @return version information (each string in the array is displayed on a separate line)
   * @throws Exception an exception detailing what went wrong when obtaining version information
  */
  String[] getVersion() throws Exception;
}
```

And currently Picocli calls `versionProvider.getVersion()`. Here is the upgraded version provider using `default`:

```java
public interface IVersionProvider {

  /**
   * Returns version information for a command.
   * @apiNote Method to be removed; implement {@link #getVersion(CommandSpec)} instead.
   * @return version information (each string in the array is displayed on a separate line)
   * @throws Exception an exception detailing what went wrong when obtaining version information
   * @deprecated This method will be removed in a future version; do not implement in new code.
  */
  default String[] getVersion() throws Exception {
    throws new UnsupportedOperationException("Version provider not correctly implemented.");
  }

  /**
   * Returns version information for a command.
   * @apiNote New code should overwrite this methdo and not {@link #getVersion()}.
   * @implSpec The default version calls {@link #getVersion()} for backwards-compatibility.
   * @return version information (each string in the array is displayed on a separate line)
   * @throws Exception an exception detailing what went wrong when obtaining version information
  */
  default String[] getVersion(CommandSpec command) throws Exception {
    return getVersion();
  }

}
```

In this scenario Picocli would `versionProvider.getVersion(commandSpec)` directly. No runtime type checking. No reflection. Just a simple call.

* Old code that implements `IVersionProvidergetVersion()`. Will continue to function 100% normally. (The compiler will indicate that the method has been deprecated, but this is only a warning. A good warning!
* New code will override `IVersionProvidergetVersion(CommandSpec)` and ignore `IVersionProvidergetVersion()`. The default implementation of `IVersionProvidergetVersion()` would still throw an exception, but _nothing would be calling that method_, so it wouldn't make any difference. Then you could just remove that method altogether from the interface in the future.
* Everybody will be happy.

**Comment by garretwilson** [comment]
P.S. See https://blog.codefx.org/java/new-javadoc-tags/ for the new Javadoc tags I used above.

**Comment by remkop** [comment]
I stand corrected. You are right. I was thinking of a different implementation but yours is much better.

So, thinking about how to proceed with this, these are the options I see:

1. Leave things as they are now, that is, postpone until picocli stops supporting pre-Java 8 runtimes (but there is no plan to do this). Meanwhile, users who need this can use [this workaround](https://github.com/remkop/picocli/issues/629#issuecomment-472274765) or [this one](https://github.com/remkop/picocli/issues/629#issuecomment-478087533).
2. Provide reusable version provider functionality now, without relying on Java 8 technology.

_Side note: Interestingly, when discussing binary compatibility in [Evolving API interfaces - API methods](https://wiki.eclipse.org/Evolving_Java-based_APIs_2#Evolving_API_interfaces_-_API_methods), the Eclipse wiki mentions that adding a default method to an interface that clients can implement is [considered a breaking change](https://wiki.eclipse.org/Evolving_Java-based_APIs#Example_4_-_Adding_an_API_method) (because the client implementation may already contain its own method with that name). They do note that "in practice, if the likelihood of this kind of name coincidence is sufficiently low, this kind of change is often treated as if it were non-breaking." I think it's fine to consider this non-breaking, but it was a good reminder._

For option 2, we won't be able to achieve a solution as elegant as with Java 8. Concrete ideas that were proposed so far (and a new one):

* introduce a new interface (name TBD) that extends `IVersionProvider` and adds a method `getVersion(CommandSpec) : String[]`. This is flexible but requires users to implement two methods instead of just one.
* introduce a new abstract class that provides a no-op implementation of `IVersionProvider.getVersion()` and a new abstract method `getVersion(CommandSpec) : String[]`.
* do both: the abstract class can implement the new interface. Client code needing flexibility can implement the interface, client code looking for convenience can extend the abstract class.

Picocli would check at runtime whether the version provider provides the new functionality, and invokes the `getVersion(CommandSpec)` method if it is available. This meets all requirements:
* new users can choose to continue to create multiple per-command version providers, or instead choose to create a single reusable version provider that provides version info for all commands
* existing version provider implementations continue to work (using some vocabulary from [Evolving Java-based APIs](https://wiki.eclipse.org/Evolving_Java-based_APIs): the new API is "contract compatible" with the old API: none of the preconditions, postconditions or invariants of the `getVersion()` method have changed)

I think having a reusable version provider is a useful feature, so I don't like the option of putting this off indefinitely. Out of the concrete ideas proposed so far, I like the abstract class best. If users ask for more flexibility, we can always later take the separate step of adding a new interface with the `getVersion(CommandSpec)` method and let the abstract class implement this interface.

I agree that the abstract class solution is not in line with the Liskov substitution principle. However, I don't think that is too much of a concern because I don't consider `IVersionProvider` a general-purpose interface with any consumers (callers) other than picocli.

**Comment by remkop** [comment]
Fresh idea: why not leave the current `IVersionProvider` API unchanged, and provide the desired context by injecting the `CommandSpec`? 

Picocli [already does this](https://picocli.info/#__code_spec_code_annotation) for `@Command`-annotated classes. 

For `IVersionProvider` implementations, picocli could inject the correct `CommandSpec` value immediately before calling `getVersion`. An implementation could look like this:

```java
class ResourcesVersionProvider implements IVersionProvider {
    @Spec CommandSpec spec;

    public String[] getVersion() throws Exception {
        // ...
    }
}
```

Thoughts?

**Comment by garretwilson** [comment]
Sorry for the huge lag in response, but as you can probably relate to, I'm super-busy with lots of projects. I'm just now coming back to this to soon release a new version of the [Guise Mummy](https://guise.io/mummy/) static site generator using the new picocli 4.x.

> Fresh idea: why not leave the current `IVersionProvider` API unchanged, and provide the desired context by injecting the `CommandSpec`?

That sounds like a good idea. Using the `CommandSpec` I could then get a reference to the class that is annotated by the command, and therefore load the correct resource bundle relative to that class, right?

It sounds like a great solution.

But is it already available? You mention it works for `@Command`-annotated classes, but I'm inferring you were waiting for my response before implementing it for `IVersionProvider`? 😞 Oops.

Well, the workaround I'm currently using works, but it sure would be nice to make it more elegant and reduce the boilerplate needed for creating new CLI applications.

Any reason you couldn't simply inject every interface instance used by picocli before you use it?

**Comment by remkop** [comment]
Hi @garretwilson, no worries about response time. I can relate. :-)

There is a `@Spec` annotation which I plan to reuse for this, but it is currently only injected into command classes, not in the version provider implementation class. This will take some work, including updating the annotation processor. Not huge, I just did not get around to it yet. 

For now I would suggest you go with the workaround you mentioned, so then hopefully a later picocli version will allow you to remove some code.

**Comment by garretwilson** [comment]
> This will take some work, including updating the annotation processor.

Might it be possible/desirable to reuse some of the Java dependency injection annotations? They are used in e.g. JAX-RS. See e.g. [`javax.inject.Inject`](https://javaee.github.io/javaee-spec/javadocs/javax/inject/Inject.html). I don't want to get into a big discussion about dependencies, but I thought I'd mention it in case you didn't know about it.

**Comment by remkop** [comment]
I know about them, and like you said, I want to avoid dependencies in picocli. :-)

**Comment by garretwilson** [comment]
> … I want to avoid dependencies in picocli

Maven allows you to mark it as an optional dependency. If someone doesn't want to use them, they don't have to.

You could dynamically try to load the class at runtime (as I assume you do with other things like `Path`) and only look for the annotations if they have been used as a dependency.

There are lots of options. It just seems a shame to invent your own when there is already a standard approach out there. Or you could offer both.

Anyway like I said I don't want to start a big discussion about dependencies, and I'm trying not to. It's slightly off topic for this ticket anyway. I'm just throwing out suggestions.

**Comment by remkop** [comment]
Support for injecting  `@Spec CommandSpec xx` into `IVersionProvider` implementations has landed in master. Please give it a try and let me know if there is any issue.

Example of what is now possible:

```java
static class SpecInjectedVersionProvider implements CommandLine.IVersionProvider {
    @Spec CommandSpec spec;

    public String[] getVersion() {
        return new String[] { "Version info for " + spec.qualifiedName() };
    }
}
```

Verified by this test:

```java
@Test
public void testCommandLine_SpecInjectedVersionProvider() {
    @Command(name = "versioned", versionProvider = SpecInjectedVersionProvider.class, version = "ignored")
    class Versioned {
        @Command(versionProvider = SpecInjectedVersionProvider.class, version = "sub ignored")
        void sub() {}
    }

    CommandLine commandLine = new CommandLine(new Versioned());
    StringWriter sw = new StringWriter();
    commandLine.printVersionHelp(new PrintWriter(sw), CommandLine.Help.Ansi.OFF);
    assertEquals(String.format("Version info for versioned%n"), sw.toString());

    sw = new StringWriter();
    commandLine.getSubcommands().get("sub").printVersionHelp(new PrintWriter(sw), CommandLine.Help.Ansi.OFF);
    assertEquals(String.format("Version info for versioned sub%n"), sw.toString());
}
```

**Comment by remkop** [comment]
Reopening: still need to write docs.

**Comment by remkop** [comment]
@garretwilson, All,

[picocli 4.2.0](https://github.com/remkop/picocli/releases/tag/v4.2.0) has been released, including [this feature](https://picocli.info/#_dynamic_version_information). Enjoy!
