### ISSUE TITLE
Generated GraalVM reflection configuration can exclude Jansi Console

### ISSUE THREAD

**Issue by shanetreacy** [remkop/picocli#645]
When generating the reflection configuration by running the generateGraalReflectionConfig gradle task, the AnsiConsole class is picked up and included in the output.

```
  {
    "name" : "org.fusesource.jansi.AnsiConsole",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "fields" : [
      { "name" : "out" }
    ]
  }
```
Giving this error when attempting to generate a nativeImage
```
error: Error parsing reflection configuration in blah/build/cli-reflect.json:
Class org.fusesource.jansi.AnsiConsole not found
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ReflectionConfigurationFiles.
Error: Image building with exit status 1
```
Manually removing the AnsiConsole block from the reflection configuration allows native image to build successfully.

Similar to issue #630

**Comment by remkop** [comment]
This problem does not occur if the jansi jar is included in the classpath when generating the GraalVM native image.

I understand that this is not strictly necessary because GraalVM does not yet support native images for Windows, so it is probably okay to exclude the `org.fusesource.jansi.AnsiConsole` class from the generated reflect.json file. (It'll be interesting to see what happens when running the resulting native image when system property `"os.name"` is set to `"Windows"`.)

Do you think you will be able to provide a pull request for this?

**Comment by remkop** [comment]
Pushed to master.
This will be included in 4.0.0-alpha-3 and later.

**Comment by remkop** [comment]
Reopening since Graal GA was released in the last few days with native-image capabilities for Windows.
This means that it makes sense to include Jansi again in some cases.

I will add a command line flag for the `gen-reflect-config` tool to optionally include configuration for the `org.fusesource.jansi.AnsiConsole` class. This flag will be `false` by default, so users need to explicitly request it to be included. I will update the documentation accordingly.

**Comment by remkop** [comment]
Actually, I found a better way to do this.

picocli can now detect whether Jansi was installed without reflecting on any Jansi classes.
This has two advantages:
* avoids loading the Jansi classes, so no native libraries are loaded (avoiding issues like #630)
* no need to include configuration for `org.fusesource.jansi.AnsiConsole` in the `reflect-config.json` file
