### ISSUE TITLE
Stop variable arity from consuming parameters

### ISSUE THREAD

**Issue by d-thomson** [remkop/picocli#659]
Is there a way to quantify arity or index parameters so options don't consume parameter values? Consider the following option and parameter:

`@Option(names = "-a", arity = "0..1") String a;`
`@Parameters(paramLabel = "file") String inputFile;`

A call such as:
`
<command> -a myFile.txt
`

Will throw a missing required parameter error. Any solution or workaround to this without reordering options? say for this case the inputFile is required to be the last arg.

Thanks!

**Comment by d-thomson** [comment]
Solved it by plucking the file out of the arguments then running the options separately. But adding greedy/lazy quantifiers for arity would be a cool feature.

**Comment by remkop** [comment]
One thing that end users can do is to specify the `--` [end-of-options delimiter](https://picocli.info/#_double_dash_code_code). The following input to your program would be interpreted correctly by picocli:

```
<command> -a -- myFile.txt
```

Variable arity tends to introduce ambiguities like this. If you really want to define your command as described, you may want to include something in the usage help about the `--` end-of-options delimiter. It is [standard](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02) in unix utilities but perhaps not that well-known...

----

FYI, picocli does have logic to detect when to stop consuming parameters for an option: if it detects that a subcommand or another option was specified, it won't consume that argument as option parameter.

For example:

```java
@Option(names = "-a", arity = "0..2") String[] a;
@Option(names = "-b") boolean b;
```

If the end user specifies this input, picocli knows `1` is a parameter for the `-a` option, but `-b` is not:
```
<cmd> -a 1 -b
```
In your example, since `inputFile` is a positional parameter and not an option, picocli has no way to make that distinction...

**Comment by d-thomson** [comment]
Appreciate the follow up and all that you do! Your second example is an excellent solution. 

Thanks!
