### ISSUE TITLE
Double printing argument group members in usage

### ISSUE THREAD

**Issue by daharon** [remkop/picocli#688]
Version:  `4.0.0-alpha-2`

When showing the usage (help) for an application that is using the new `ArgGroup` feature,
the members of the argument group are printed twice.

For instance, if an `ArgGroup` contains members `foo` and `bar`, then the usage will print the following:
```Usage: <main class> [--foos=FOO[,FOO...] [--foos=FOO[,FOO...]]... --bars=BAR[,BAR...] [--bars=BAR[,BAR...]]...]```

Example:
https://gist.github.com/daharon/e6b303c643c1a286830067e7d848e888

**Comment by remkop** [comment]
@daharon, the reason you're seeing the options twice in the synopsis is that they are `required` and multi-value options. (The `split` attribute makes it look even more verbose...)

## Minimal example

```java
@Command(name = "cmd")
class App {
  @Option(names = "-a", required = true, paramLabel = "AAA")
  List<String> a;
}
```
This will show the following synopsis:

```
Usage: cmd -a=AAA [-a=AAA]...
``` 
The synopsis shows that this option must be specified at least once (because it is `required`) and may be specified multiple times after that (because its type is `List`, making it multi-value).

## Arg Groups

Argument groups are optional (`multiplicity = "0..1"`) by default. This is shown by rendering the group options in `[` and `]` brackets in the synopsis. 

When the group is required (`multiplicity = "1"`), the synopsis shows `(` and `)` brackets instead.


## Heading
One more thing: the group heading should end in `%n` to get a line break after the heading text.

Tthis is for consistency with the other headings; for example, the `Usage: ` synopsis heading is usually on the same line without a `%n` at the end.

## Larger Example (Without Groups)

```java
@Command(name = "issue688", description = "Synopsis test",
        optionListHeading = "Options%n",
        parameterListHeading = "Positional Parameters%n"
)
class App {
    @Parameters(paramLabel = "POSITIONAL", arity = "1..*", split = ",",
            description = "Specify at least one, each value may be a " +
                    "comma-separated list of values.")
    List<String> positionals;

    @Option(names = {"-a", "--aaa"}, paramLabel = "AAA", required = true,
            description = "This required option may be specified multiple times.")
    List<String> requiredFoos;

    @Option(names = {"-b", "--bbb"}, paramLabel = "BBB", required = true, split = ",",
            description = "This required option may be specified multiple times, " +
                    "and each value may be a comma-separated list of values.")
    List<String> requiredBars;

    @Option(names = {"-c", "--ccc"}, paramLabel = "CCC",
            description = "This option may be specified multiple times.")
    List<String> foos;

    @Option(names = {"-d", "--ddd"}, paramLabel = "DDD", split = ",",
            description = "This option may be specified multiple times, " +
                    "and each value may be a comma-separated list of values.")
    List<String> bars;
}
```

This will print the following usage help:

```
Usage: issue688 -a=AAA [-a=AAA]... -b=BBB[,BBB...] [-b=BBB[,BBB...]]...
                [-c=CCC]... [-d=DDD[,DDD...]]... POSITIONAL[,POSITIONAL...]...
Synopsis test
Positional Parameters
      POSITIONAL[,POSITIONAL...]...
                           Specify at least one.
Options
  -a, --aaa=AAA            This required option may be specified multiple times.
  -b, --bbb=BBB[,BBB...]   This required option may be specified multiple times, and
                             each value may be a comma-separated list of values.
  -c, --ccc=CCC            This option may be specified multiple times.
  -d, --ddd=DDD[,DDD...]   This option may be specified multiple times, and each
                             value may be a comma-separated list of values.
```

I hope this clarifies, let me know what you think.

**Comment by daharon** [comment]
@remkop, so since I don't want the option listed multiple times, it sounds like the type should not be `List`.

Playing around some more, I cannot figure out how to correctly configure this.

What I want are two options, `--foo` and `--bar`, to be co-dependent.
With each option taking a comma-separated list of values.

So I'm expecting the usage to look like this:  
```
[--foos=FOO[,FOO...] --bars=BAR[,BAR...]]
```

**Comment by remkop** [comment]
I see. Please be aware that multi-value options may be specified multiple times. For example:

```
--foo 111 --foo 222 --foo 333 --bar AAA,BBB,CCC
```

The above is valid input for your example and will result in 3 values in the `foo` list and 3 values in the `bar` list. 

Is this what you have in mind?

One alternative is to make the type of `foo` and `bar` simple `String`s (instead of a `List`), and set the `paramLabel = "FOO[,FOO...]"` to get the desired synopsis. The drawback is that you’ll need to split the values into comma-separated parts in the application.

**Comment by daharon** [comment]
@remkop, Ok I understand the design now.
I'll stick with the way it is.
Thanks.

**Comment by remkop** [comment]
You’re welcome!
Please star the project on GitHub if you like it. ;-)
