### ISSUE TITLE
[Question] Run commands over Rest web service

### ISSUE THREAD

**Issue by decebals** [remkop/picocli#823]
First of all congratulations, it's nice piece of software.
I am new to picocli, so maybe my question is not so smart 😄.

My application is an web application built with [Pippo](http://www.pippo.ro) (micro web framework) and [PF4J](https://pf4j.org) (plugin system).
The idea is that you can extend the comand list of application via plugins and you can call each plugin in a standard mode using a generic http entry point.
More specifically, I have an entry point in my web application like:
```java
GET("/shell", routeContext -> {
    // retrieve "cmd" parameter from request
    String cmd = routeContext.getParameter("cmd").toString();

    // execute "cmd" on server
    CommandResult result = getCommandService().execute(cmd);

    // send the response
    routeContext.send(result)
);
```
On client side (a tiny web client application), I will call the above "shell" entry point using a web client in a secure mode.

My question for you is how I can implement the `CommandService#execute(String cmd)` method in a simple mode.

See below my skeleton/pseudocode of this method:
```java
public CommandResult execute(String cmd) {
    // 1. identify and run the picocli's command for "cmd"
    // 2. wrap/pack the result of command execution in a CommandResult
    // 3. return the result
}
````

Another question is how I can configure the picocli and make it known all the commands available in the application.

Each command extends a `AcmeCommand` that contains some methods to inject some services:
```java
public abstract class AcmeCommand extends ExtensionPoint {

    // generate getters and setters    
    private ServiceX serviceX;
    private ServiceY servicey;

}
```

where `ExtensionPoint` is a marker interface from `PF4J` that specify that command is an extension point in application.

When someone wants to add a new command in application/system, he should add a new class in a new plugin and mark the class as extension:
```java
@Extension
public class ImportFromCsv extends AcmeCommand implements Callable<Integer> {

    @Option
    String option1;

    public Integer call() throws Exception {
        return getServiceX().doSomething(option1);
    }

}
```

where `@Extension` is an annotation marker in `PF4J` that marks `ImportFromCsv` as extension of application.

The list with all commands can be retrieved in application with:
```java
List<AcmeCommand> commands = pluginManager.getExtensions(AcmeCommand.class);
```

So, I have all the ingredients for a scalable/modular command system that can execute commands over HTTP in a secure mode. What is missing is the picocli's glue. Because I am new to picocli, I don't know for the moment how to write the glue 😄.

Any advice is welcome. Thanks!

If you need more details, I am happy to help.

**Comment by remkop** [comment]
@decebals Glad you like picocli! Let me try to answer your questions.

> how I can implement the `CommandService#execute(String cmd)` method

Let's analyze the input and output.

Input from the web client will be a single String (`cmd`), but picocli expects an array of String arguments. So the incoming `cmd` String needs to be tokenized.
You can implement this yourself with `java.io.StreamTokenizer`, 

or use JLine3's `DefaultParser` (see [this example](https://github.com/remkop/picocli/tree/master/picocli-shell-jline3))):

```java
String[] args = new DefaultParser().parse(cmd, 0).words().toArray(new String[0]);
```
 
or JLine2's `WhitespaceArgumentDelimiter` see [this example](https://github.com/remkop/picocli/tree/master/picocli-shell-jline2)):

```java
String[] args = new WhitespaceArgumentDelimiter().delimit(cmd, cmd.length()).getArguments();
```

Now we have an array of Strings.

> (How do we) identify and run the picocli's command for "cmd"

I assume that the first element of the String[] array is the command that we want to execute.

I propose that you let picocli do the work. You can do that by modeling all supported commands as subcommands of some (internal) top-level command. Let me give a concrete example.

Suppose your web service supports 3 commands: `aaa`, `bbb` and `ccc` (each may have some options and positional parameters, maybe even subcommands).
I propose that you create a top-level command (let's call it `shell`), and give it 3 subcommands: `aaa`, `bbb` and `ccc`.
Now, given the user input String array ["aaa", "-option1=123", "-option2=456", "positionalarg1"], picocli will detect that the `aaa` subcommand was invoked with arguments "-option1=123", "-option2=456" and "positionalarg1". This is exactly what we want.

> how I can configure picocli and tell it all the commands available in the application

Any commands that are known in advance could be [hardcoded](https://picocli.info/#_registering_subcommands_declaratively) into the `Shell` top-level command with annotations. For example:

```java
@Command(name = "shell",
  subcommands = {Aaa.class, // list up the known commands here
                 Bbb.class,
                 Ccc.class})
class Shell implements Callable<Integer> {
    @Spec CommandSpec spec;
    public Integer call() {
        // The top-level command itself does not do anything. We need a subcommand.
        // If missing, print error message to STDERR followed by the usage help message.
        throw new ParameterException(spec.commandLine(), "Missing required command");
    }
}

// ...
CommandLine commandLine = new CommandLine(new Shell());
int exitCode = commandLine.execute(args);
```

Any commands that are _not_ known in advance can be [added programmatically](https://picocli.info/#_registering_subcommands_programmatically). For example:

```java
CommandLine commandLine = new CommandLine(new Shell())
        .addSubcommand(new Aaa())
        .addSubcommand(new Bbb())
        .addSubcommand(new Ccc());
int exitCode = commandLine.execute(args);
```

> return the result

The output of each command may have several components:

* exit status code
* any output printed to STDOUT
* any error messages printed to STDERR
* maybe some custom object created in the command?

The exit code of any subcommand is returned by the `CommandLine.execute` method, so that part is easy.

To capture STDOUT and STDERR, there are 2 options:

1. You can configure the `CommandLine` to use a custom `PrintWriter` for STDOUT and STDERR so you can capture the output:

```java
StringWriter out = new StringWriter();
StringWriter err = new StringWriter();

CommandLine commandLine = new CommandLine(new Shell())
        .setOut(new PrintWriter(out))
        .setErr(new PrintWriter(err));
int exitCode = commandLine.execute(args);

CommandResult commandResult = new CommandResult();
commandResult.setExitCode(exitCode);
commandResult.setOutput(out.toString());
commandResult.setErrors(err.toString());
// ...
```

Of course, this means that the business logic of your commands should not write directly to `System.out` and `System.err`, but instead **they must use the picocli writers**:

```java
@Command(name = "aaa")
class Aaa implements Callable<Integer> {
    @Spec CommandSpec spec;

    @Option(name = "-option1") int option1;

    public Integer call() {
        spec.commandLine().getOut().println("My results are: 123 and 456");
        if (option1 < 0) {
            spec.commandLine().getErr().println("Error: option1 must be a positive number");
        }
    }
}
```

2. Alternatively, you can leave picocli and the command implementations to write to the default STDOUT and STDERR streams, and replace them at the `System` level:

```java
PrintStream oldOut = System.out;
PrintStream oldErr = System.err;

try {
    ByteArrayOutputStream out = new ByteArrayOutputStream();
    ByteArrayOutputStream err = new ByteArrayOutputStream();
    System.setOut(new PrintStream(out));
    System.setErr(new PrintStream(err));

    CommandLine commandLine = new CommandLine(new Shell());
    int exitCode = commandLine.execute(args);

    CommandResult commandResult = new CommandResult();
    commandResult.setExitCode(exitCode);
    commandResult.setOutput(out.toString());
    commandResult.setErrors(err.toString());
    // ...
} finally {
    System.setOut(new PrintStream(oldOut));
    System.setErr(new PrintStream(oldErr));
}
```

This last approach has the advantage that command implementations can use the idiomatic `System.out.println("output")` and `System.err.println("error")`, but has the drawback that if you are running your webapp in a JVM that is shared with other (web) applications, anything that the other threads write to STDOUT and STDERR will also be captured.

I hope this helps to get you started.

**Comment by decebals** [comment]
@remkop 
Thanks for your detailed explanation.
