### ISSUE TITLE
Formatting Problem

### ISSUE THREAD

**Issue by habanoz** [remkop/picocli#842]
Formatting is broken when of incorrect arguments are given. This is not happening if connection is local, it happens if connection is to a remote system.

https://drive.google.com/file/d/1WQdLIhZLsENweSSV1xjaE6_vTvJjMJV_/view?usp=sharing

What might be the reason behind this? Any suggestion to fix ?

Thanks

**Comment by remkop** [comment]
Can you provide some more information? 

* What version of picocli are you using?
* Does the application [specify the width](https://picocli.info/#_usage_width) of the usage help message? (Either in the annotations with `@Command(usageHelpWidth = 80)` or programmatically.)

You mentioned a "connection to a remote system". Can you give more information about this connection? For example, 

* what protocol (SSH, Telnet?) and what OS and application do you use locally (Windows-10 built-in SSH in DOS console, or Ubuntu Open-SSH in Bash terminal, other...?)
* What OS and application is used on the remote side?

From what I can see in the image file, the remote side is sending text with unix-style embedded newlines: only "line feed" (0x0A, or `\n`) characters, and no "[carriage return](https://en.wikipedia.org/wiki/Carriage_return)" (0x0d, or `\r`) characters. It appears that the local application interprets that by moving the cursor one line down and not returning to the beginning of the line.

Could it be that the application you are using locally needs to be configured to expect `\n` instead of `\r\n`?

**Comment by habanoz** [comment]
My local system is windows 10. 

Using  version 4.0.4.  "usageHelpWidth" is not used.

 Picocli and apache sshd used together to create  a ssh interface. If I run the application locally in my windows system and connect to ssh interface output is well formatted.

If I run the application in a remote system and connect to that remote system using ssh command then connecting to the applications ssh interface (using ssh 127.0.0.1 -p),  I observe the issue. 

I tried with putty and mobaxterm, result is the same.

> Could it be that the application you are using locally needs to be configured to expect \n instead of \r\n?

I will focus on this. In the mean time closing the issue, will reopen later.

**Comment by remkop** [comment]
Sounds like an interesting app. Good luck, and let me know if there's anything that needs to change on the picocli side.
