### ISSUE TITLE
Use ANSI colors and styles in error handlers

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#845]
Use ANSI colors and styles in error handlers. For example:

* show invalid usage error messages in bold and red by default
* TBD what style to use for the stack trace printed for execution exceptions and unhandled exceptions

It may make sense to update the `CommandLine.Help.ColorScheme` class to make these configurable.

**Comment by jerrylususu** [comment]
Hello! I'm considering to contribute to this project, and I'd like to know whether the issue is open to pull request. Is there any suggestions for implementing this feature?

**Comment by remkop** [comment]
Hello, thank you for considering contributing! 
PRs are welcome, especially if they have tests and ideally documentation. 
I haven’t thought about implementation, but it may not be easy... :-)

**Comment by jerrylususu** [comment]
I'm trying to implement this function, but I meet some design decisions, and would like to know what's the best way in your mind.

My current plan is:
1. Add 2 attributes `errors` and `stackTraces` to `ColorScheme`
2. Change `internalHandleParseException` method, let writer write `colorScheme.errorText(ex.getMessage())`, instead of just `ex.getMessage()`, so argument parse error can get the ANSI color required.
3. Create a default implementation of `IExecutionExceptionHandler`, customize a `ColoredPrintWriter` with `ColorScheme` or `IStyle[]` in constructor, and when invoking `ex.printStackTrace`, instead of using `cmd.getErr()`, use the new ColoredPrintWriter instead.

However, designing in such way will lead to some problems:
1. `ColorScheme` contains color settings beyond help info, so it might be necessary to move `ColorScheme` to the same layer of `Help`, to show that `ColorScheme` represents general settings of ANSI colors. But doing so will introduce some serious incompatibility problems when users want to update picocli to new version.
2. As the exception message is part of the stack trace, hacking `PrintWriter` will make the exception message has the same style as the stack trace, which might not be intended behavior.

I would like to know what do you think, so I can move forward. Thanks!

By the way, here is a peek of my current progress. I'm using `Style.fg_red` and `Style.bold` for parse errors, and `Style.italic` for stack traces.

![image](https://user-images.githubusercontent.com/17522475/80103404-c38bb600-85a6-11ea-8257-f71e87301942.png)

**Comment by jerrylususu** [comment]
Thanks for your great suggestions! Therefore, I will just keep `ColorScheme` in `Help`, and try to implement the `IExecutionExceptionHandler` in a reasonable way. By the way, do I need to include all the testings on my first pull request, or I can add them to the pull request later?

**Comment by jerrylususu** [comment]
After digging into the source code more, I made some changes to my original plan:

1. Instead of implementing a default `ExecutionExceptionHandler`, I chose to change the `handleUnhandled` function. By adding a method called `exceptionToColorString`, I can convert exception to ANSI colored string according to the current ColorScheme.

2. Instead of print stack traces to a string, I looked into how Java handles exception stack trace printing (`printStackTrace` method in `Throwable.java`), and emulated the default behavior, but with the message and stack traces colored.

Besides, I also update the comments in code, and update tests to reflect my changes. All the tests should pass now. I didn't wrote any new test, as I'm not sure how to... Could you please give some suggestions on this? As for the documentations, I'm not sure where they are in the repo, so that part was not touched.

Finally, I'm worried about whether this change may break compatibility, as some programs using the output from stderr (log analyzer...) might not play well with ANSI control sequences. I'm not sure if the default values for the new introduced `errors` and `stackTraces` should be set, or just remain empty.

Here is a preview of how it looks in the end.
![image](https://user-images.githubusercontent.com/17522475/80285329-abf32f80-8756-11ea-8c0b-f5aa9924f868.png)

**Comment by remkop** [comment]
The PR has been merged into master.
Thank you for the contribution!
