### ISSUE TITLE
How do I configure global options for all subcommands?

### ISSUE THREAD

**Issue by li-wjohnson** [remkop/picocli#895]
I've seen similar issues around, but I'm looking to make it easier to have some global options that call for some setup.  The obvious use case here is logging. This issue isn't about how to specify global options (e.g. an option that works for all subcommands), but rather how to run some setup based on a parent option for all subcommands.

Say I have a command, `main`, with some subcommands `foo` and `bar`. If you just run `main`, it prints help. `main` supports `-v[vvvv]`, which changes the log level for all subcommands, e.g. `main -vv foo`.

Where is the right place to put this logging setup to get this functionality?  I'd rather not have to modify every subcommand to explicitly call the parent (or grandparent, etc.) command to get the log level or call setup. I could put it in `main`'s `call()` method, and use `setExecutionStrategy(new RunAll())`. This is the most intuitive -- each parent command can do some setup for all of its subcommands, letting you build a hierarchy and logically group common functionality. However, then I'm not sure how to invoke help if you call a parent command without a subcommand.

(In comparison to python's click, you define `groups`, which are commands that support subcommands. If you execute a group's subcommand, the group method is invoked, allowing you to call some global setup. However if you try to execute a group directly [`main`], it just prints help. This is also configurable, so that a group *can* be executed directly: https://click.palletsprojects.com/en/7.x/commands/#group-invocation-without-command)

**Comment by li-wjohnson** [comment]
I figured out one solution:

  ```
@CommandLine.Spec
 CommandLine.Model.CommandSpec spec;

  public Integer call() {
    CommandLine commandLine = spec.commandLine();
    if (!commandLine.getParseResult().hasSubcommand()) {
      commandLine.usage(System.err);
      return 1;
    }
    ... do setup here ...
  }
```

I've refactored this into a Mixin. Now every 'group' command will first call that mixin method to print help if invoked without any subcommand, and otherwise do whatever setup it needs. I think there's room for improvement here in terms of how these 'group' commands are handled and such, but at least there's a workaround through less-documented APIs.

**Comment by remkop** [comment]
That is certainly one solution. Another one I could think of is to have the log level option implemented as a setter method on the parent command:

```java
class MainCommand {

    @Option(names = "-v")
    public void setVerbosity(boolean[] newVerbosity) {
        // update global log level
    }
}
```

**Comment by li-wjohnson** [comment]
Does that solution work when they don't specify '-v'? does `setVerbosity()` get called in that case?

**Comment by remkop** [comment]
No, you’re right, it may not be that useful; apart from your observation, the method will get called multiple times if `-v` is specified multiple times on the command line, and that makes it less convenient to use for initialization. 

The more I look at it, the more I like your solution.

**Comment by garretwilson** [comment]
Is this the issues that we discussed forever and ever on #649?

**Comment by wjohnson5** [comment]
There's two separate issues.

#649, from what I can tell, is asking for 'main foo --debug', without having to define --debug for foo. (Maybe I'm misreading it?) This feature would be nice to have, so it doesn't matter where a user puts the --debug flag.

This issue is different - can we make it easier to configure things from options specified in the parent command? Considering that the 'runLast()' execution strategy is the default, the only hook we have is if you make the parent option a setter method, but that has the drawbacks mentioned above (only invoked if the option is specified, repeated invocations). That means every subcommand has the do the work of checking the parent command's options and doing setup. 

#649 is definitely relevant. If it was implemented such that parent options could also be specified in subcommands, we could do 'main foo -vv'. But as I see it, the '-vv' option is still specified for the parent command, and we'd still have this issue for how to actually configure things (e.g. logging) using that option.

**Comment by wjohnson5** [comment]
The elegance of the runAll() approach is that the command that defines the option is the one that does the work of reading that option, rather than every subcommand doing it via @ParentCommand. But then I had the question of how to change the behavior of the parent command if it's called directly (print help) vs called with a subcommand (do common setup). That's solvable with the ParseResult, but it'd still be nice to make this setup easier or at least documented.

**Comment by wjohnson5** [comment]
(whoops, commenting with different accounts, sorry 😁)

**Comment by garretwilson** [comment]
> This issue is different - can we make it easier to configure things from options specified in the parent command?

Ah, so I would consider it the same issue, it's just that you need only half of what I need. Let me restate the use case:

There needs to be a way to configure cross-cutting concerns (such as log level, log filename and other log configuration, debug mode, and locale/language) in a common way across commands. This consists of two parts:
1. The ability to define such parameters related to these concerns across multiple commands without repeating definitions.
2. The ability to consolidate implementation of these concerns across multiple command without repeating code.

If I understand you correctly, this ticket #895 is only about the second aspect, while my request #649 was about both aspects. (It's been a while, so I'd have to reread my ticket #649 completely, but this is close enough for now.)

Both aspects are important to me, but frankly I'll take what I can get. Even if I had to redefine the commands, if there was some way that the logic would automatically be called to implement them it would really help.

For example, the following is actual code from my Guise Mummy static site generator:

```java
@Command(description = "Mummifies a site by generating a static version.", subcommands = {HelpCommand.class})
public void mummify(
  @Parameters(paramLabel = "<project>", description = "The base directory of the project to mummify.%nDefaults to the working directory, currently @|bold ${DEFAULT-VALUE}|@.", defaultValue = "${sys:user.dir}", arity = "0..1") @Nullable Path argProjectDirectory,
  @Option(names = "--site-source-dir", description = "The source root directory of the site to mummify.%nDefaults to @|bold src/site/|@ relative to the project base directory.") @Nullable Path argSiteSourceDirectory,
  @Option(names = "--site-target-dir", description = "The target root directory into which the site will be generated; will be created if needed.%nDefaults to @|bold target/site/|@ relative to the project base directory.") @Nullable Path argSiteTargetDirectory,
  @Option(names = "--site-description-target-dir", description = "The target root directory into which the site description will be generated; will be created if needed.%nDefaults to @|bold target/site-description/|@ relative to the project base directory.") @Nullable Path argSiteDescriptionTargetDirectory,
  @Option(names = {"--debug", "-d"}, description = "Turns on debug level logging.") final boolean debug) throws IOException {

  setDebug(debug); //TODO inherit from base class; see https://github.com/remkop/picocli/issues/649
```

(Yes, I even have the `TODO` in the code.)

While it would be nice not to redefine the `--debug` flag here, it would sure be helpful at least not to need to add the boilerplate of `setDebug(debug)` somehow.

Is that close to what you want? If not I'll be quiet here and stick to discussing this in #649.

**Comment by wjohnson5** [comment]
Yeah, that's about right - I missed that point number 2. Since you need to define --debug for each subcommand, you need to reimplement it everywhere. But this issue is that, even if you don't redefine --debug everywhere, every subcommand needs to implement it's handling.

**Comment by remkop** [comment]
@li-wjohnson @garretwilson 

[picocli 4.2.0](https://github.com/remkop/picocli/releases/tag/v4.2.0) has just been released.
It adds support for `@ParentCommand`-annotated fields in mixins. This allows creating mixins with `@Option`-annotated methods that delegate to the parent command. I added an example showing how to [share options between commands and subcommands](https://picocli.info/#_use_case_sharing_options) to the user manual. 

I would like to also add an example for your use case: configuring logging.

I have a [draft example in the wiki](https://github.com/remkop/picocli/wiki/Configuring-Logging-in-a-CLI-App), that uses a custom execution strategy which first configures logging, and then runs the `CommandLine.RunLast` execution strategy. 

(The advantage of this solution over using `RunAll` and configuring logging in the `run` method of the top-level command is that this will not execute intermediate commands in applications with deeper command hierarchies that have more than 2 levels.)

If you have any ideas on improving this before I add it to the manual, feedback would be very welcome!

**Comment by garretwilson** [comment]
@remkop , thanks for the notification, and I apologize that it will be a while before I am able to look at this in depth. But just glancing at the [example](https://picocli.info/#_use_case_sharing_options), it seems pretty verbose (not pun intended with the example), and it doesn't seem to match up with the needs I mentioned. And this chaining up the command hierarchy seems convoluted.

Maybe you're down in the details so much you're missing the bigger picture. Please read about [cross-cutting concerns](https://en.wikipedia.org/wiki/Cross-cutting_concern). Then think about this very reasonable use case:

* Every CLI extends from some `BaseCli` class.
* The `BaseCli` class configures cross-cutting concerns, such as logging, user locale, etc.
* The actual `MyCli` app doesn't know or care and should even have to think about what the base class did to set up cross-cutting concerns.
* The `MyCli` app simply adds command _methods_ as needed. They all get the cross-cutting concern parameters. _Automatically._ (You could add a feature that allows a command to _remove_ or _replace_ a cross-cutting concern parameter.)

Done. End of story. It's simple. And it's not a far-fetched use case. I would say it is a use case that applies to 80% of CLI applications or more! (Most CLIs don't elegantly set up cross-cutting concerns because it's so difficult.)

I fear that your example has forgotten much of the things we discussed in #649. To make this simpler, here, just look at a real, live, application, released just a few weeks ago:

https://github.com/globalmentor/guise/blob/master/cli/src/main/java/io/guise/cli/GuiseCli.java

See all the nasty:

```java
setDebug(debug); //TODO inherit from base class; see https://github.com/remkop/picocli/issues/649
```

That application extends the base application here:

https://github.com/globalmentor/globalmentor-application/blob/master/src/main/java/com/globalmentor/application/BaseCliApplication.java

If your new approach solves this, then wonderful, and sorry for being slow to understand. But just looking at it, it still seems complicated (and the "will not execute intermediate commands in applications with deeper command hierarchies that have more than 2 levels" comment above makes me fear the main point of cross-cutting concerns). Unfortunately it will several weeks before I can try this out and comment further. But thanks for letting me know the news.

**Comment by remkop** [comment]
@garretwilson Thanks for the feedback.

The "will not execute intermediate commands in applications with deeper command hierarchies that have more than 2 levels" comment was specifically about how the  [draft example in the wiki](https://github.com/remkop/picocli/wiki/Configuring-Logging-in-a-CLI-App) uses a custom execution strategy (in the `main` method) which first configures logging, and then runs the `RunLast` execution strategy. I believe this custom strategy is better than using the `RunAll` execution strategy to configure logging because with the `RunAll` strategy you may end up executing more commands than desired if you have more than 2 levels. I mention this because the `RunAll` strategy is what @li-wjohnson and I came up with originally for this ticket.

With regards to `GuiseCli`, the calls to `setDebug` from the command methods could be avoided by replacing the `@Option(names = {"--debug", "-d"}) boolean debug` options with a Mixin that delegates to the parent. This reduces the duplication to a single `@Mixin SomeClass someParam` method parameter. I understand this is more verbose than you requested/proposed, but I am very uncomfortable with the 4th point in your use case description:

> The `MyCli` app simply adds command _methods_ as needed. They all get the cross-cutting concern parameters. _Automatically._ (You could add a feature that allows a command to _remove_ or _replace_ a cross-cutting concern parameter, I suppose.)

I understand the theory of cross-cutting concerns, but I also like code that one can understand what it does by looking at it. Command methods that automatically (without asking for it) get extra options and parameters lack that property. This means maintainers must understand _the whole system_ in order to reason about how _part of the system_ works. Each part may have some aspect/cross-cutting concern automatically applied to it that changes its behaviour, but maintainers cannot tell just by looking at that part. I am not convinced that the more concise code is a good trade-off for the potentially surprising behaviour.

The Mixin solution is an explicit opt-in mechanism for sharing options and functionality. Commands that don't want a cross-cutting concern can opt out by not having the mixin - so no need for another mechanism to _remove_ cross-cutting concerns. The fact that it is explicit (and not automatic) means that it is easier to read the code and reason about what it does. Having to code an extra Mixin class to delegate to the parent is a reasonable trade-off in my opinion.

**Comment by garretwilson** [comment]
@remkop as always thanks for reading my thoughts and for the reply.

> I understand the theory of cross-cutting concerns, but I also like code that one can understand what it does by looking at it. …  Each part may have some aspect/cross-cutting concern automatically applied to it that changes its behaviour, but maintainers cannot tell just by looking at that part. I am not convinced that the more concise code is a good trade-off for the potentially surprising behaviour.

We should distinguish between "cross-cutting concerns", which is merely away to characterize certain functionality to better understand it; and "aspect-oriented programming", which is a common way people propose to _implement_ cross-cutting concerns. I share your worries in principle about code that does surprising things, and for this reason I currently don't advocate aspect-oriented programming, where new code springs up "between the lines" as it were, out of the blue. In fact I'm even very leery of dependency injection; I think it is very useful but also prone to over-use. I'm not proposing aspect-oriented programming or even DI (which you already implement).

> Command methods that automatically (without asking for it) get extra options and parameters lack that property. This means maintainers must understand the whole system in order to reason about how part of the system works.

If we take what you're saying at face value, then you are basically saying that we should prohibit normal object inheritance and polymorphism!! Because after all, if I if I extend `BaseWidget`, then suddenly I get a `munge()` method without doing anything! Suddenly `BaseWidget` does all sorts of initialization without my asking it to! And suddenly I must "understand the whole system in order to reason about how part of the system works"!

But of course I don't have to understand "the whole system". I only have to understand how `BaseWidget` works to know what initialization it does, and what default functionality it brings. _That's why I made the decision to extend `BaseWidget` to begin with!_ And to understand `BaseWidget` I merely read its API documentation.

I'm not proposing some spooky "action at a distance", to use quantum theory as a metaphor, where some functionality mysteriously appears in some remote part of my program.  I'm just wanting normal OO inheritance to work!

> The Mixin solution is an explicit opt-in mechanism for sharing options and functionality. … Having to code an extra Mixin class to delegate to the parent is a reasonable trade-off in my opinion.

I think the mixin approach is a wonderful improvement, allowing anyone to mix-and-match functionality explicitly, anywhere a developer wants, event without extending some base class. That's great! 👍 Thank you for that feature.

But in the case where someone would _like_ to consolidate several mixins in a base class (this is OOP 101), so that developers can extend the subclass (because they want to, having read the API documentation—not because they were surprised by some mystery), then I don't see how it would hurt to allow mixins to be declared at the parent class level. Or do you not like abstract classes and interface default methods, either?

**Comment by remkop** [comment]
We seem to be on the same page about avoiding code that does surprising things, that’s good. 

> If we take what you're saying at face value, then you are basically saying that we should prohibit normal object inheritance and polymorphism!! (...) I'm just wanting normal OO inheritance to work!

Normal OO inheritance is fine, because if I declare a `class A extends Base` then `A` explicitly _asks for_ `Base`’s functionality. There’s nothing surprising, that’s how class inheritance works. 

The relationship that picocli commands have to subcommands is very different from inheritance:
* a parent command declares its subcommands, not the other way around. Subcommands don’t ask to have some specific parent command.
* the only semantic of the “parent command-subcommand” relationship is “subcommand may follow parent command”.  There’s no expectation of having shared options or shared other attributes.

Because of this difference, I think it would be confusing if subcommands would inherit options from the parent command. 

It is certainly possible to consolidate several mixins in a base class so that developers can extend it in their subclass. If we’re extending classes we’re back in normal OO territory. No surprises here. 

However, if I understood correctly, your request was to let a `@Command`-annotated _method_ inherit options/parameters from its parent command. I think that’s too confusing so I propose to use mixins instead.

**Comment by remkop** [comment]
I added an updated [example in `picocli-examples`](https://github.com/remkop/picocli/tree/master/picocli-examples/src/main/java/picocli/examples/logging), demonstrating how to configure logging from a global `--verbose` option.

@li-wjohnson, please take a look: instead of using the `RunAll` execution strategy, this example shows how a method reference (`LoggerMixin::executionStrategy` in the example) can be set as the execution strategy. From this method you can do your configuration logic before calling `RunLast`. For example:

```
class MyApp {
  public static void main(String... args) {
    MyApp app = new MyApp();
    new CommandLine(app).setExecutionStrategy(app::executionStrategy).execute(args);
  }

  private int executionStrategy(ParseResult parseResult) {
    configureLogging();
    return new CommandLine.RunLast().execute(parseResult);
  }

  private void configureLogging() { ... } // set log level from verbosity here
}
```

@garretwilson As commented on https://github.com/remkop/picocli/issues/649, I am coming around to the idea of providing a convenience API for global options with something like `@Option(global = true)`. One drawback of that API is that there is no way for a subcommand to "opt out". That is fine, as long as there is an alternative. The example shows that alternative. (You may not be interested in this, so feel free to ignore the below.)

The example shows the `@Mixin` approach for providing global options; this requires each command to explicitly "opt in" with the `@Mixin` syntax, so gives applications more fine-grained control over which commands take the option.

This example is less verbose than my previous attempt and no longer uses `@ParentCommand` to chain up the command hierarchy. It relies on a new feature to be introduced in picocli 4.3, that allows a mixin class to declare a CommandSpec field like this:

```java
private @Spec(Spec.Target.MIXEE) CommandSpec spec;
```

The `MIXEE` target indicates that the `CommandSpec` to inject is not the spec of the enclosing class, but the spec of the command where the `@Mixin` is used. This allows the mixin to climb the command hierarchy and store the "verbosity" value in a single place. The log level is then configured from that single value.

**Comment by remkop** [comment]
@li-wjohnson I updated the user manual: https://picocli.info/#_initialization_before_execution

I believe that addresses the topic of this ticket.
Feel free to open another one or comment here if there is still work remaining or anything else.
