### ISSUE TITLE
Make long options column width configurable (was: usageHelpWidth isn't affecting the the params list)

### ISSUE THREAD

**Issue by tomerz90** [remkop/picocli#934]
Example output:
```
  -h, --help                Show this help message and exit.
  --output=<outputFolder>
                            Output location full path
```
Im using:
```
@Command(mixinStandardHelpOptions = true, usageHelpWidth = 200)
```
It stays the same, doesnt matter what value I put instead of 200.
The only part the width is affecting is the first line:
```
Usage: <main class> ...
```
What I'm trying to achieve is consistency, with having all the descriptions start in the same line as the flag, or not, but not have a mix of both.

**Comment by remkop** [comment]
Thank you for raising this. 

The layout of the options list is currently not very flexible. Let's see how we can improve on this.

Currently the max length of the column containing long options and positional parameters is fixed at 20. I've put [some effort](https://github.com/remkop/picocli/issues/360) into making the minimum length dynamic, so that the column shrinks if all long options are very short. However, there is no way to tell picocli to allocate _more_ space to this column.

I'm thinking to make the maximum length of that column configurable. API-wise, that would look something like this:

```java
@Command(name = "myapp", mixinStandardHelpOptions = true)
class MyApp {
    @Option(names = {"-o", "--output"}, description = "Output location full path")
    File outputFolder;

    public static void main(String[] args) {
        new CommandLine(new MyApp())
                .setUsageHelpLongOptionsMaxWidth(25)
                .execute(args);
    }
}
```

The semantics of the new `setUsageHelpLongOptionsMaxWidth` method would be that "it controls the maximum width of the long options column: any positional parameter labels or long options that are longer than the specified value will overflow into the description column, and cause the description to be displayed on the next line".

Thoughts?

**Comment by tomerz90** [comment]
Sounds good, thanks!
Personally, Im using just the part of parsing config (`CommandLine.parseSpec`) so it would be nice if this would also be configurable for the flow, maybe through the `Command` annotation.
Also, does the description width also have a hard-coded limit?

**Comment by remkop** [comment]
The description width is calculated as the remaining width, it can grow if a larger width is specified.
I am missing something, what is `parseSpec`? Did you mean `parseArgs`?
You should still be able to do 

```java
new CommandLine(new MyApp())
        .setUsageHelpLongOptionsMaxWidth(25)
        .parseArgs(args);
```

I am not sure yet about adding it to the `@Command` annotation.

**Comment by tomerz90** [comment]
Sorry, I meant `CommandLine.populateSpec`

**Comment by remkop** [comment]
I see.

**Comment by remkop** [comment]
Actually, I don’t see... :-)

Don’t you still need to do something like this to print the usage help?

```
new CommandLine(new MyApp()).usage(System.out);
```

So you might as well call the new method on the `CommandLine` object.

**Comment by tomerz90** [comment]
Yes, you are right, never mind then.

**Comment by remkop** [comment]
An initial fix for this has landed in master.
The updated manual page is [here](https://github.com/remkop/picocli/blob/master/docs/index.adoc#long-option-column-width).

You can test by checking out the latest master and building with:

```
gradlew clean publishToMavenLocal
```

That should publish `picocli-4.2.0-SNAPSHOT` to your local .m2 Maven cache. You can then try this in a project that uses the `info.picocli:picocli:4.2.0-SNAPSHOT` dependency.

Feedback very welcome!

**Comment by remkop** [comment]
@tomerz90 , All,

[picocli 4.2.0](https://github.com/remkop/picocli/releases/tag/v4.2.0) has been released, including [this feature](https://picocli.info/#_long_option_column_width). Enjoy!
